import type { CatalogExercise } from '../program-types';

/**
 * Arm exercise library (R10): biceps, triceps, and forearms. Preserves
 * Overhead Cable Triceps Extension, Triceps Pressdown, Incline Dumbbell
 * Curl, Cable Curl, and Dumbbell Curl from the pre-R10 catalog verbatim
 * (name/category/muscles/progression/guidance untouched), adding only
 * muscleGroup, equipment, and defaultPrescription. Every other entry is new
 * library content.
 */
export const ARM_EXERCISES: CatalogExercise[] = [
  // --- Biceps: barbell and machine ---
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    category: 'hypertrophy',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    progressionType: 'double-progression',
    muscleGroup: 'biceps',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your biceps stretch fully at the bottom and contract hard at the top, with your torso staying still.',
    cues: [
      'Keep your elbows pinned at your sides',
      'Curl the bar up without swinging your torso',
      'Squeeze the biceps hard at the top',
      'Lower under control to a full stretch',
    ],
    commonMistakes: [
      'Swinging the torso and hips to help lift the weight',
      'Letting the elbows drift forward as the set gets hard',
      'Cutting the bottom stretch short',
    ],
    substitutions: ['ez-bar-curl', 'dumbbell-curl', 'cable-curl'],
  },
  {
    id: 'ez-bar-curl',
    name: 'EZ Bar Curl',
    category: 'hypertrophy',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    progressionType: 'double-progression',
    muscleGroup: 'biceps',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel the same full biceps stretch and contraction as a straight bar curl, with less strain on the wrists from the angled grip.',
    cues: [
      'Keep your elbows pinned at your sides',
      'Curl up without swinging your torso',
      'Squeeze the biceps hard at the top',
      'Lower under control to a full stretch',
    ],
    commonMistakes: [
      'Swinging the torso to help lift the weight',
      'Letting the elbows drift forward',
      'Rushing the lowering phase',
    ],
    substitutions: ['barbell-curl', 'dumbbell-curl'],
  },
  {
    id: 'machine-curl',
    name: 'Machine Curl',
    category: 'hypertrophy',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'biceps',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your biceps working through a fixed, supported path, without needing to stabilize the weight or resist swinging.',
    cues: [
      'Set the seat so your elbows line up with the pivot point',
      'Curl through a full range without lifting your elbows off the pad',
      'Squeeze hard at the top',
      'Control the return to a full stretch',
    ],
    commonMistakes: [
      'Lifting the elbows off the pad to help finish the rep',
      'Using momentum to jerk the weight up',
      'Only using the top half of the range',
    ],
    substitutions: ['barbell-curl', 'cable-curl'],
  },

  // --- Biceps: dumbbell and cable ---
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    category: 'hypertrophy',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel your biceps stretch fully at the bottom and contract fully at the top of each rep.',
    cues: [
      'Keep your elbows close to your torso throughout',
      'Curl the dumbbells up without swinging your shoulders',
      'Squeeze the biceps at the top',
      'Lower under control to a full stretch',
    ],
    commonMistakes: [
      'Using body swing or momentum to move the weight',
      'Letting the elbows drift forward as the weight gets heavy',
      'Cutting the bottom stretch short',
    ],
    muscleGroup: 'biceps',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    substitutions: ['barbell-curl', 'hammer-curl', 'cable-curl'],
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    category: 'hypertrophy',
    primaryMuscles: ['biceps', 'brachialis'],
    secondaryMuscles: ['forearms'],
    progressionType: 'double-progression',
    muscleGroup: 'biceps',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel more thickness through the outer arm and forearm than a standard curl, from the neutral grip biasing the brachialis.',
    cues: [
      'Hold the dumbbells with palms facing your torso throughout',
      'Keep your elbows pinned at your sides',
      'Curl up without rotating the wrist',
      'Lower under control to a full stretch',
    ],
    commonMistakes: [
      'Rotating the wrist and turning it into a standard curl',
      'Swinging the torso to help lift the weight',
      'Letting the elbows drift forward',
    ],
    substitutions: ['dumbbell-curl', 'reverse-curl'],
  },
  {
    id: 'incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    category: 'hypertrophy',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel a deep stretch in your biceps at the bottom and a full squeeze at the top.',
    cues: [
      'Let your arms hang straight down from the incline bench',
      'Curl without swinging your elbows forward',
      'Squeeze the biceps hard at the top of the curl',
      'Lower slowly to feel the full stretch',
    ],
    commonMistakes: [
      'Letting the elbows drift forward to reduce the stretch',
      'Using body momentum to swing the weight up',
      'Rushing the lowering phase and skipping the stretch',
    ],
    muscleGroup: 'biceps',
    equipment: ['dumbbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    substitutions: ['dumbbell-curl', 'spider-curl'],
  },
  {
    id: 'preacher-curl',
    name: 'Preacher Curl',
    category: 'hypertrophy',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'biceps',
    equipment: ['barbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel a strong stretch at the bottom with your upper arms locked against the pad, removing any ability to swing.',
    cues: [
      'Rest your upper arms fully against the pad',
      'Lower until you feel a full stretch, but stop before the elbows hyperextend',
      'Curl up and squeeze hard at the top',
      'Control the descent rather than letting the weight drop',
    ],
    commonMistakes: [
      'Lifting the upper arms off the pad to cheat the rep',
      'Lowering into full elbow hyperextension',
      'Bouncing out of the bottom stretch',
    ],
    substitutions: ['spider-curl', 'ez-bar-curl'],
  },
  {
    id: 'spider-curl',
    name: 'Spider Curl',
    category: 'hypertrophy',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'biceps',
    equipment: ['dumbbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel constant biceps tension with your upper arms hanging straight down over the bench, removing any help from the shoulders.',
    cues: [
      'Lean chest first against the incline bench with arms hanging straight down',
      'Curl up without letting the upper arms drift forward',
      'Squeeze hard at the top',
      'Lower under control to a full stretch',
    ],
    commonMistakes: [
      'Letting the upper arms swing forward off the pad',
      'Using momentum to help finish the rep',
      'Cutting the range short at the top or bottom',
    ],
    substitutions: ['preacher-curl', 'incline-dumbbell-curl'],
  },
  {
    id: 'concentration-curl',
    name: 'Concentration Curl',
    category: 'hypertrophy',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'biceps',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15, perSide: true },
    intendedFeeling:
      'You should feel one arm working in complete isolation, with your elbow braced against your leg removing any body swing.',
    cues: [
      'Brace your elbow against the inside of your thigh',
      'Curl up without letting the elbow drift off your leg',
      'Squeeze hard at the top of the curl',
      'Lower under control to a full stretch',
    ],
    commonMistakes: [
      'Letting the elbow lift off the leg to cheat the rep',
      'Using the torso to help swing the weight',
      'Rushing through reps instead of a controlled squeeze',
    ],
    substitutions: ['dumbbell-curl', 'preacher-curl'],
  },
  {
    id: 'cable-curl',
    name: 'Cable Curl',
    category: 'hypertrophy',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel constant tension in your biceps through the whole range, since the cable never lets the weight rest.',
    cues: [
      'Keep your elbows pinned at your sides',
      'Curl up under control without swinging',
      'Squeeze at the top of the movement',
      'Lower slowly rather than letting the cable snap back',
    ],
    commonMistakes: [
      'Swinging the torso to help lift the weight',
      'Letting the elbows drift forward or back',
      'Only working the top half of the range',
    ],
    muscleGroup: 'biceps',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    substitutions: ['bayesian-cable-curl', 'dumbbell-curl', 'barbell-curl'],
  },
  {
    id: 'bayesian-cable-curl',
    name: 'Bayesian Cable Curl',
    category: 'hypertrophy',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'biceps',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15, perSide: true },
    intendedFeeling:
      'You should feel a deep stretch at the bottom from the cable pulling your arm behind your torso, with the squeeze concentrated at the top.',
    cues: [
      'Face away from the low pulley with your arm trailing slightly behind your torso',
      'Let the cable pull your arm back for a full stretch before curling',
      'Curl up and forward, squeezing hard at the top',
      'Lower under control back to the stretched position',
    ],
    commonMistakes: [
      'Standing too close to the pulley and losing the behind-torso stretch',
      'Swinging the torso to help finish the curl',
      'Rushing the eccentric and skipping the stretch',
    ],
    substitutions: ['cable-curl', 'dumbbell-curl'],
  },
  {
    id: 'reverse-curl',
    name: 'Reverse Curl',
    category: 'hypertrophy',
    primaryMuscles: ['brachialis', 'forearms'],
    secondaryMuscles: ['biceps'],
    progressionType: 'double-progression',
    muscleGroup: 'biceps',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel the top of your forearm and brachialis working harder than in a standard curl, from the overhand grip.',
    cues: [
      'Grip the bar with palms facing down',
      'Keep your elbows pinned at your sides',
      'Curl up without rotating the wrist',
      'Lower under control to a full stretch',
    ],
    commonMistakes: [
      'Using too much weight and losing wrist position',
      'Swinging the torso to help lift the weight',
      'Letting the elbows drift forward',
    ],
    substitutions: ['hammer-curl', 'barbell-curl'],
  },

  // --- Triceps: pressing variations ---
  {
    id: 'close-grip-bench-press',
    name: 'Close-Grip Bench Press',
    category: 'strength',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'triceps',
    equipment: ['barbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 10 },
    intendedFeeling:
      'You should feel your triceps driving the press with a narrower grip than a standard bench press, with your chest assisting.',
    cues: [
      'Grip just inside shoulder width',
      'Keep your elbows tucked close to your torso as you lower',
      'Lower the bar to your lower chest',
      'Press up by extending through the elbows first',
    ],
    commonMistakes: [
      'Gripping too narrow and straining the wrists',
      'Flaring the elbows out wide, losing the triceps emphasis',
      'Bouncing the bar off the chest',
    ],
    substitutions: ['barbell-bench-press', 'skull-crusher', 'jm-press'],
  },
  {
    id: 'skull-crusher',
    name: 'Skull Crusher',
    category: 'hypertrophy',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'triceps',
    equipment: ['barbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel a deep stretch in your triceps as the bar lowers toward your forehead, with your upper arms staying vertical and still.',
    cues: [
      'Keep your upper arms vertical and still throughout',
      'Lower the bar toward your forehead or just behind it',
      'Extend through the elbows only to press back up',
      'Control the descent rather than dropping the bar',
    ],
    commonMistakes: [
      'Letting the upper arms drift back toward the face',
      'Using the shoulders to help move the weight',
      'Lowering too fast and losing control near the head',
    ],
    substitutions: ['jm-press', 'dumbbell-overhead-extension', 'overhead-cable-triceps-extension'],
  },
  {
    id: 'jm-press',
    name: 'JM Press',
    category: 'hypertrophy',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest'],
    progressionType: 'double-progression',
    muscleGroup: 'triceps',
    equipment: ['barbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 10 },
    intendedFeeling:
      'You should feel a hybrid of a close-grip press and a skull crusher, with the triceps under heavy tension through a shortened, controlled range.',
    cues: [
      'Start with a close grip similar to a close grip bench press',
      'Lower the bar toward your upper chest and chin, elbows tucking as it descends',
      'Keep the movement controlled rather than reaching for a big range',
      'Press back up by extending the elbows',
    ],
    commonMistakes: [
      'Losing control of the bar path since it is a hybrid, unfamiliar movement',
      'Flaring the elbows out wide',
      'Using too much weight before the pattern is grooved',
    ],
    substitutions: ['skull-crusher', 'close-grip-bench-press'],
  },
  {
    id: 'dumbbell-overhead-extension',
    name: 'Dumbbell Overhead Extension',
    category: 'hypertrophy',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'triceps',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel a deep stretch in your triceps overhead, with your upper arms staying close to your head throughout.',
    cues: [
      'Pin your upper arms close to your head and keep them still',
      'Lower the dumbbell behind your head until you feel a full stretch',
      'Extend through the elbows only, straightening fully at the top',
      'Keep your core braced so your torso does not sway',
    ],
    commonMistakes: [
      'Letting the elbows flare out to the sides',
      'Using the shoulders to help swing the weight',
      'Stopping short of full extension at the top',
    ],
    substitutions: ['overhead-cable-triceps-extension', 'skull-crusher'],
  },
  {
    id: 'overhead-cable-triceps-extension',
    name: 'Overhead Cable Triceps Extension',
    category: 'hypertrophy',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel the stretch and contraction concentrated in your triceps, with your upper arms staying still.',
    cues: [
      'Pin your upper arms close to your head and keep them still',
      'Lower the weight until you feel a full stretch in the triceps',
      'Extend through the elbows only, straightening fully at the top',
      'Keep your core braced so your torso does not sway',
    ],
    commonMistakes: [
      'Letting the elbows drift forward or flare out',
      'Using the shoulders to help swing the weight',
      'Stopping short of full elbow extension at the top',
    ],
    muscleGroup: 'triceps',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    substitutions: ['dumbbell-overhead-extension', 'triceps-pressdown'],
  },

  // --- Triceps: pressdowns and dips ---
  {
    id: 'triceps-pressdown',
    name: 'Triceps Pressdown',
    category: 'hypertrophy',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel the stretch and contraction concentrated in your triceps as your forearms extend.',
    cues: [
      'Pin your elbows at your sides and keep them still',
      'Press down until your arms are fully extended',
      'Squeeze the triceps hard at full extension',
      'Control the return to a full stretch',
    ],
    commonMistakes: [
      'Letting the elbows drift away from the body',
      'Using the shoulders to help push the weight down',
      'Cutting the stretch short at the top of the movement',
    ],
    muscleGroup: 'triceps',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    substitutions: ['rope-pressdown', 'single-arm-cable-pressdown'],
  },
  {
    id: 'rope-pressdown',
    name: 'Rope Pressdown',
    category: 'hypertrophy',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'triceps',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel an extra squeeze at the bottom as the rope splits apart, on top of the usual triceps pressdown contraction.',
    cues: [
      'Pin your elbows at your sides and keep them still',
      'Press down and split the rope ends apart at the bottom',
      'Squeeze the triceps hard at full extension',
      'Control the return to a full stretch',
    ],
    commonMistakes: [
      'Letting the elbows drift away from the body',
      'Skipping the rope split at the bottom',
      'Using the shoulders to help push the weight down',
    ],
    substitutions: ['triceps-pressdown', 'single-arm-cable-pressdown'],
  },
  {
    id: 'single-arm-cable-pressdown',
    name: 'Single-Arm Cable Pressdown',
    category: 'hypertrophy',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'triceps',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15, perSide: true },
    intendedFeeling:
      'You should feel one triceps working in isolation through a full stretch and squeeze, with your torso staying square.',
    cues: [
      'Pin your elbow at your side and keep it still',
      'Press down until your arm is fully extended',
      'Squeeze hard at full extension',
      'Control the return to a full stretch',
    ],
    commonMistakes: [
      'Letting the elbow drift away from the torso',
      'Rotating the torso to help finish the rep',
      'Cutting the stretch short at the top',
    ],
    substitutions: ['triceps-pressdown', 'rope-pressdown'],
  },
  {
    id: 'kickback',
    name: 'Kickback',
    category: 'hypertrophy',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'triceps',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 12, maxReps: 20, perSide: true },
    intendedFeeling:
      'You should feel a strong squeeze in your triceps at the top as your arm extends straight back, with your upper arm staying fixed and parallel to the floor.',
    cues: [
      'Hinge forward and keep your upper arm parallel to the floor',
      'Keep your upper arm fixed and still throughout',
      'Extend your forearm straight back until your arm is fully straight',
      'Lower under control rather than letting the weight swing',
    ],
    commonMistakes: [
      'Swinging the upper arm instead of keeping it fixed',
      'Using momentum from the torso to help extend',
      'Not reaching full extension at the top',
    ],
    substitutions: ['triceps-pressdown', 'dumbbell-overhead-extension'],
  },
  {
    id: 'upright-dip',
    name: 'Upright Dip',
    category: 'calisthenics',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'triceps',
    equipment: ['dip-bars'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 15 },
    intendedFeeling:
      'You should feel your triceps driving the lockout with your torso kept upright, biasing the triceps over the chest.',
    cues: [
      'Keep your torso as upright as possible throughout',
      'Lower until your shoulders dip just below your elbows',
      'Keep your elbows tracking back, not flared wide',
      'Press up through full extension without swinging',
    ],
    commonMistakes: [
      'Leaning forward and shifting the work to the chest',
      'Descending so deep it strains the front of the shoulder',
      'Using a leg swing to help finish the rep',
    ],
    substitutions: ['bench-dip', 'close-grip-bench-press'],
  },
  {
    id: 'bench-dip',
    name: 'Bench Dip',
    category: 'calisthenics',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'triceps',
    equipment: ['bodyweight', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 20 },
    intendedFeeling:
      'You should feel your triceps working through a controlled range with your feet on the floor or elevated, easier on the shoulders than a full dip.',
    cues: [
      'Keep your hips close to the bench throughout the movement',
      'Lower until your upper arms are roughly parallel to the floor',
      'Keep your elbows tracking straight back, not flared',
      'Press up through full extension',
    ],
    commonMistakes: [
      'Letting the hips drift forward away from the bench',
      'Descending too deep and straining the front of the shoulder',
      'Using leg drive instead of the triceps to finish the rep',
    ],
    substitutions: ['upright-dip', 'triceps-pressdown'],
  },
  {
    id: 'machine-triceps-extension',
    name: 'Machine Triceps Extension',
    category: 'hypertrophy',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'triceps',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your triceps working through a fixed, supported path without needing to stabilize the weight.',
    cues: [
      'Set the seat so your elbows line up with the pivot point',
      'Extend through the elbows without lifting them off the pad',
      'Squeeze hard at full extension',
      'Control the return to a full stretch',
    ],
    commonMistakes: [
      'Lifting the elbows off the pad to help finish the rep',
      'Using momentum to jerk the handles down',
      'Only using the top half of the range',
    ],
    substitutions: ['triceps-pressdown', 'overhead-cable-triceps-extension'],
  },

  // --- Forearms and grip ---
  {
    id: 'wrist-curl',
    name: 'Wrist Curl',
    category: 'hypertrophy',
    primaryMuscles: ['forearms'],
    secondaryMuscles: ['grip'],
    progressionType: 'double-progression',
    muscleGroup: 'forearms',
    equipment: ['dumbbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20 },
    intendedFeeling:
      'You should feel the underside of your forearm contracting as your wrist curls up, with your forearm resting still against the bench.',
    cues: [
      'Rest your forearms on a bench with your wrists just past the edge',
      'Let the weight lower until you feel a full stretch',
      'Curl your wrist up as high as it will go',
      'Lower slowly under control',
    ],
    commonMistakes: [
      'Using the elbow or forearm to help swing the weight',
      'Only using a short, rushed range of motion',
      'Gripping so hard the wrist barely moves',
    ],
    substitutions: ['reverse-wrist-curl'],
  },
  {
    id: 'reverse-wrist-curl',
    name: 'Reverse Wrist Curl',
    category: 'hypertrophy',
    primaryMuscles: ['forearms'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'forearms',
    equipment: ['dumbbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20 },
    intendedFeeling:
      'You should feel the top of your forearm contracting as your wrist extends up, a lighter and slower movement than a standard wrist curl.',
    cues: [
      'Rest your forearms on a bench, palms facing down',
      'Let the weight lower until you feel a full stretch on top of the forearm',
      'Extend your wrist up as high as it will go',
      'Lower slowly under control',
    ],
    commonMistakes: [
      'Using too much weight and losing range of motion',
      'Letting the forearm lift off the bench to help',
      'Rushing the tempo instead of a controlled extension',
    ],
    substitutions: ['wrist-curl'],
  },
  {
    id: 'farmer-hold',
    name: 'Farmer Hold',
    category: 'hypertrophy',
    primaryMuscles: ['forearms', 'grip'],
    secondaryMuscles: ['traps', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'forearms',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'duration', sets: 3, minSeconds: 30, maxSeconds: 60 },
    intendedFeeling:
      'You should feel your grip and forearms working to keep the weight from slipping, with your torso staying tall and braced.',
    cues: [
      'Stand tall with your shoulders pulled back',
      'Grip the weights hard and keep your knuckles facing forward',
      'Brace your core and walk or stand without leaning to either side',
      'Set the weight down under control when grip starts to fail',
    ],
    commonMistakes: [
      'Letting the shoulders round forward under the load',
      'Leaning to one side to compensate for grip fatigue',
      'Dropping the weight instead of setting it down under control',
    ],
    substitutions: ['plate-pinch-hold'],
  },
  {
    id: 'plate-pinch-hold',
    name: 'Plate Pinch Hold',
    category: 'hypertrophy',
    primaryMuscles: ['forearms', 'grip'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'forearms',
    equipment: ['other'],
    defaultPrescription: { type: 'duration', sets: 3, minSeconds: 20, maxSeconds: 40 },
    intendedFeeling:
      'You should feel your fingertips and forearm working hard just to keep the plates pinched together without slipping.',
    cues: [
      'Pinch two plates together, smooth sides out, using your fingertips',
      'Keep your wrist straight rather than bent',
      'Hold at your side without letting the plates rotate or slip',
      'Set the plates down under control when grip starts to fail',
    ],
    commonMistakes: [
      'Bending the wrist to help hold the plates',
      'Using plates too heavy to hold with a clean pinch grip',
      'Letting the plates twist and slip rather than resetting the hold',
    ],
    substitutions: ['farmer-hold'],
  },
];
