import type { CatalogExercise } from '../program-types';

/**
 * Back exercise library (R10). Preserves Pull-Up, Assisted Pull-Up,
 * Chest-Supported Row, Neutral-Grip Lat Pulldown, Single-Arm Cable Row, and
 * Seated Cable Row from the pre-R10 catalog verbatim (name/category/
 * muscles/progression/guidance untouched), adding only muscleGroup,
 * equipment, and defaultPrescription. Every other entry is new library
 * content.
 */
export const BACK_EXERCISES: CatalogExercise[] = [
  // --- Vertical pulling ---
  {
    id: 'pull-up',
    name: 'Pull-Up',
    category: 'strength',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper back'],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel your lats stretching at the bottom and driving your elbows down on the way up, with your biceps assisting.',
    cues: [
      'Start from a full hang with shoulder blades relaxed',
      'Initiate the pull by driving your elbows down and back',
      'Pull until your chin clears the bar',
      'Lower under control back to a full stretch',
    ],
    commonMistakes: [
      'Kipping or swinging to get the chin over the bar',
      'Only using a partial range at the top or bottom',
      'Letting the shoulders shrug up instead of the lats initiating',
    ],
    muscleGroup: 'back',
    equipment: ['pull-up-bar'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 10 },
    substitutions: ['assisted-pull-up', 'chin-up', 'neutral-grip-lat-pulldown'],
  },
  {
    id: 'assisted-pull-up',
    name: 'Assisted Pull-Up',
    category: 'strength',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper back'],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel the same lat stretch and pull as a standard pull up, just with the assistance taking the load off at the sticking points.',
    cues: [
      'Use only as much assistance as needed to complete full range reps',
      'Start from a full hang each rep',
      'Drive your elbows down and back to initiate the pull',
      'Lower under control rather than letting the assistance do the negative',
    ],
    commonMistakes: [
      'Using more assistance than needed and short changing the range',
      'Bouncing off the bottom of the assist platform',
      'Letting momentum from the platform substitute for the pull',
    ],
    muscleGroup: 'back',
    equipment: ['machine', 'pull-up-bar'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 12 },
    substitutions: ['pull-up', 'neutral-grip-lat-pulldown'],
  },
  {
    id: 'chin-up',
    name: 'Chin-Up',
    category: 'strength',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper back'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['pull-up-bar'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 10 },
    intendedFeeling:
      'You should feel more biceps involvement than a pull up, with your lats still doing the majority of the pulling work.',
    cues: [
      'Start from a full hang with an underhand grip',
      'Pull your elbows down toward your hips',
      'Pull until your chin clears the bar',
      'Lower under control to a full stretch',
    ],
    commonMistakes: [
      'Swinging or kipping to finish the rep',
      'Only using a partial range',
      'Letting the shoulders shrug instead of the lats initiating',
    ],
    substitutions: ['pull-up', 'weighted-pull-up'],
  },
  {
    id: 'weighted-pull-up',
    name: 'Weighted Pull-Up',
    category: 'strength',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper back'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['pull-up-bar', 'other'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 4, maxReps: 8 },
    intendedFeeling:
      'You should feel the same full lat stretch and pull as a bodyweight pull up under additional external load.',
    cues: [
      'Secure the added weight before starting the set',
      'Start every rep from a full hang',
      'Drive the elbows down and back without kipping',
      'Lower under control despite the extra load',
    ],
    commonMistakes: [
      'Adding weight before bodyweight reps are fully controlled',
      'Using momentum or kipping to move the extra load',
      'Cutting the range short as the set gets hard',
    ],
    substitutions: ['pull-up', 'chin-up'],
  },
  {
    id: 'wide-grip-lat-pulldown',
    name: 'Wide-Grip Lat Pulldown',
    category: 'hypertrophy',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper back'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your lats stretching wide overhead and driving the bar down to your chest, with minimal arm involvement.',
    cues: [
      'Grip just outside shoulder width',
      'Lean back only slightly, keep your chest up',
      'Pull your elbows down and back, driving them toward your hips',
      'Let the bar rise under control to a full overhead stretch',
    ],
    commonMistakes: [
      'Leaning back excessively and turning it into a row',
      'Pulling mainly with the arms instead of the lats',
      'Yanking the bar down with body momentum',
    ],
    substitutions: ['neutral-grip-lat-pulldown', 'pull-up', 'single-arm-lat-pulldown'],
  },
  {
    id: 'neutral-grip-lat-pulldown',
    name: 'Neutral-Grip Lat Pulldown',
    category: 'hypertrophy',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps'],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel your lats stretching overhead and driving the pull down, not your arms doing most of the work.',
    cues: [
      'Lean back only slightly and keep your chest up',
      'Pull your elbows down toward your hips',
      'Drive the bar to your upper chest, squeezing your lats',
      'Let the weight rise under control to a full overhead stretch',
    ],
    commonMistakes: [
      'Leaning back excessively and turning it into a row',
      'Pulling mainly with the arms instead of the lats',
      'Using momentum from the torso to yank the bar down',
    ],
    muscleGroup: 'back',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    substitutions: ['wide-grip-lat-pulldown', 'pull-up'],
  },
  {
    id: 'single-arm-lat-pulldown',
    name: 'Single-Arm Lat Pulldown',
    category: 'hypertrophy',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'obliques'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12, perSide: true },
    intendedFeeling:
      'You should feel one side of your lat working through a full stretch and squeeze, with your torso staying still against the pull.',
    cues: [
      'Keep your torso square, resist leaning toward the cable',
      'Drive your elbow down and back toward your hip',
      'Squeeze the lat at the bottom of the pull',
      'Return under control to a full stretch',
    ],
    commonMistakes: [
      'Rotating the torso to help finish the pull',
      'Using a short range instead of a full stretch and squeeze',
      'Leaning back excessively',
    ],
    substitutions: ['neutral-grip-lat-pulldown', 'single-arm-cable-row'],
  },
  {
    id: 'straight-arm-pulldown',
    name: 'Straight-Arm Pulldown',
    category: 'hypertrophy',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['triceps', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your lats pulling the bar down in an arc while your arms stay essentially straight, isolating the lats away from the biceps.',
    cues: [
      'Keep a slight, fixed bend in your elbows throughout',
      'Hinge forward slightly at the hips before starting',
      'Sweep the bar down in an arc to your thighs',
      'Control the return to a full overhead stretch',
    ],
    commonMistakes: [
      'Bending the elbows more to turn it into a pulldown',
      'Using the torso to swing the weight down',
      'Cutting the arc short at the top or bottom',
    ],
    substitutions: ['neutral-grip-lat-pulldown', 'pull-up'],
  },

  // --- Horizontal rows: barbell and dumbbell ---
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    category: 'strength',
    primaryMuscles: ['upper back', 'lats'],
    secondaryMuscles: ['biceps', 'lower back'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 10 },
    intendedFeeling:
      'You should feel your upper back and lats driving the bar into your torso, with your lower back braced and static, not moving the weight.',
    cues: [
      'Hinge to roughly a 45 degree torso angle and hold it',
      'Row the bar toward your lower ribs or upper abdomen',
      'Drive your elbows back, not out to the sides',
      'Lower under control without losing the hinge',
    ],
    commonMistakes: [
      'Standing up taller each rep to use momentum',
      'Rounding the lower back under load',
      'Yanking the bar up with a jerking motion',
    ],
    substitutions: ['pendlay-row', 'dumbbell-row', 'chest-supported-row'],
  },
  {
    id: 'pendlay-row',
    name: 'Pendlay Row',
    category: 'strength',
    primaryMuscles: ['upper back', 'lats'],
    secondaryMuscles: ['biceps', 'lower back'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 5, maxReps: 8 },
    intendedFeeling:
      'You should feel an explosive pull from a dead stop on the floor each rep, with your upper back doing all the work, no body english.',
    cues: [
      'Set a flat back and parallel torso, and reset it every rep',
      'Let the bar rest fully on the floor between reps',
      'Pull explosively into your lower ribs',
      'Reset your position completely before the next rep',
    ],
    commonMistakes: [
      'Not resetting the torso angle between reps',
      'Using a hip pop to help start the pull',
      'Rounding the back to reach the bar',
    ],
    substitutions: ['barbell-row', 'dumbbell-row'],
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    category: 'hypertrophy',
    primaryMuscles: ['upper back', 'lats'],
    secondaryMuscles: ['biceps'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['dumbbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12, perSide: true },
    intendedFeeling:
      'You should feel one side of your back pulling the dumbbell through a full stretch and squeeze, with your torso supported and still.',
    cues: [
      'Support your torso flat on a bench with the free hand and knee',
      'Let the arm hang for a full stretch before pulling',
      'Row your elbow up and back, not straight up toward the ceiling',
      'Squeeze at the top and lower under control',
    ],
    commonMistakes: [
      'Rotating the torso to help lift the weight',
      'Using a short range instead of a full stretch and squeeze',
      'Yanking the dumbbell up with momentum',
    ],
    substitutions: ['single-arm-cable-row', 'chest-supported-row'],
  },
  {
    id: 'meadows-row',
    name: 'Meadows Row',
    category: 'hypertrophy',
    primaryMuscles: ['upper back', 'lats'],
    secondaryMuscles: ['biceps'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['barbell', 'other'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12, perSide: true },
    intendedFeeling:
      'You should feel one side of your lat and upper back through a long stretch and strong squeeze, with a more vertical pulling angle than a standard row.',
    cues: [
      'Set up perpendicular to a landmine barbell, feet staggered',
      'Let the weight travel down for a full lat stretch',
      'Pull your elbow up and back in a semicircular path',
      'Squeeze at the top before lowering with control',
    ],
    commonMistakes: [
      'Standing too square instead of staggered, limiting the range',
      'Using the legs and hips to heave the weight up',
      'Cutting the stretch short at the bottom',
    ],
    substitutions: ['dumbbell-row', 'single-arm-cable-row'],
  },
  {
    id: 't-bar-row',
    name: 'T-Bar Row',
    category: 'hypertrophy',
    primaryMuscles: ['upper back', 'lats'],
    secondaryMuscles: ['biceps', 'lower back'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['barbell', 'other'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your whole upper back thickening as you row a heavier load close to your torso, with your lower back held rigid.',
    cues: [
      'Set a strong hip hinge and hold your torso angle',
      'Row the handles into your lower chest or upper abdomen',
      'Keep your elbows close to your body, not flared',
      'Lower under control without rounding the back',
    ],
    commonMistakes: [
      'Standing up taller each rep to use momentum',
      'Rounding the lower back under load',
      'Only using a short range at the top',
    ],
    substitutions: ['barbell-row', 'chest-supported-row'],
  },
  {
    id: 'machine-row',
    name: 'Machine Row',
    category: 'hypertrophy',
    primaryMuscles: ['upper back', 'lats'],
    secondaryMuscles: ['biceps'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your back doing the pulling through a fixed, supported path, without needing to stabilize the weight or your torso.',
    cues: [
      'Set the chest pad so your arms start extended',
      'Row your elbows back and squeeze your shoulder blades together',
      'Keep your chest pressed against the pad throughout',
      'Control the return to a full stretch',
    ],
    commonMistakes: [
      'Lifting the chest off the pad to add momentum',
      'Shrugging the shoulders instead of pulling with the back',
      'Only using the top half of the range',
    ],
    substitutions: ['chest-supported-row', 'seated-cable-row'],
  },

  // --- Horizontal rows: cable ---
  {
    id: 'chest-supported-row',
    name: 'Chest-Supported Row',
    category: 'hypertrophy',
    primaryMuscles: ['upper back', 'lats'],
    secondaryMuscles: ['biceps'],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel your upper back and lats squeezing the weight in, with no help from body swing since your chest is braced against the pad.',
    cues: [
      'Keep your chest pressed into the pad the entire set',
      'Row your elbows back and let your shoulder blades come together',
      'Pause briefly when the elbows reach your torso',
      'Control the weight back out to a full stretch',
    ],
    commonMistakes: [
      'Lifting the chest off the pad to use momentum',
      'Shrugging the shoulders instead of pulling with the back',
      'Cutting the stretch short on the way out',
    ],
    muscleGroup: 'back',
    equipment: ['dumbbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    substitutions: ['dumbbell-row', 'machine-row', 't-bar-row'],
  },
  {
    id: 'single-arm-cable-row',
    name: 'Single-Arm Cable Row',
    category: 'hypertrophy',
    primaryMuscles: ['upper back', 'lats'],
    secondaryMuscles: ['biceps'],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel one side of your back working through a full stretch and squeeze, without your torso rotating to help.',
    cues: [
      'Keep your torso square, resist rotating toward the cable',
      'Row your elbow back past your ribs',
      'Squeeze your shoulder blade at the end of the pull',
      'Return under control to a full stretch',
    ],
    commonMistakes: [
      'Rotating the torso to add momentum',
      'Using a short range instead of a full stretch and squeeze',
      'Letting the shoulder shrug up toward the ear',
    ],
    muscleGroup: 'back',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12, perSide: true },
    substitutions: ['seated-cable-row', 'dumbbell-row'],
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    category: 'hypertrophy',
    primaryMuscles: ['upper back', 'lats'],
    secondaryMuscles: ['biceps'],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel your upper back and lats squeezing together as you row, with your torso staying upright and still.',
    cues: [
      'Sit tall with a slight forward lean at the start',
      'Row your elbows back and squeeze your shoulder blades together',
      'Keep your torso still, do not rock back and forth',
      'Control the return to a full stretch',
    ],
    commonMistakes: [
      'Rocking the torso to add momentum',
      'Shrugging the shoulders instead of pulling with the back',
      'Cutting the stretch short at the front of the movement',
    ],
    muscleGroup: 'back',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    substitutions: ['single-arm-cable-row', 'chest-supported-row'],
  },
  {
    id: 'inverted-row',
    name: 'Inverted Row',
    category: 'calisthenics',
    primaryMuscles: ['upper back', 'lats'],
    secondaryMuscles: ['biceps', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['bodyweight', 'other'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 15 },
    intendedFeeling:
      'You should feel your back rowing your whole rigid bodyweight up to the bar, with your core preventing any hip sag.',
    cues: [
      'Keep a straight line from head to heels',
      'Row your chest toward the bar, driving elbows back',
      'Squeeze your shoulder blades together at the top',
      'Lower under control to a full stretch',
    ],
    commonMistakes: [
      'Letting the hips sag toward the floor',
      'Only using a partial range',
      'Turning the head up instead of driving the chest to the bar',
    ],
    substitutions: ['ring-row', 'dumbbell-row'],
  },
  {
    id: 'ring-row',
    name: 'Ring Row',
    category: 'calisthenics',
    primaryMuscles: ['upper back', 'lats'],
    secondaryMuscles: ['biceps', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['rings'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 15 },
    intendedFeeling:
      'You should feel the same rowing pattern as an inverted row, with the added instability of the rings demanding extra shoulder and core control.',
    cues: [
      'Keep a straight line from head to heels',
      'Row your chest toward the rings, driving elbows back',
      'Control the ring path, avoid letting them drift apart or together',
      'Lower under control to a full stretch',
    ],
    commonMistakes: [
      'Letting the hips sag toward the floor',
      'Letting the rings swing or drift due to poor control',
      'Only using a partial range',
    ],
    substitutions: ['inverted-row', 'dumbbell-row'],
  },

  // --- Posterior chain and isometric ---
  {
    id: 'rack-pull',
    name: 'Rack Pull',
    category: 'strength',
    primaryMuscles: ['upper back', 'lower back'],
    secondaryMuscles: ['glutes', 'hamstrings', 'traps'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 4, maxReps: 8 },
    intendedFeeling:
      'You should feel your entire back bracing rigid to lock out a heavy partial pull from just below the knee, with your grip and traps also under real load.',
    cues: [
      'Set the pins so the bar starts just below your knee',
      'Set your back flat and brace hard before pulling',
      'Drive through the floor and stand tall to lockout',
      'Lower under control back to the pins',
    ],
    commonMistakes: [
      'Rounding the lower back to muscle the weight up',
      'Hyperextending at the top instead of standing tall',
      'Dropping the bar instead of controlling the descent',
    ],
    substitutions: ['barbell-row', 'romanian-deadlift'],
  },
  {
    id: 'back-extension',
    name: 'Back Extension',
    category: 'hypertrophy',
    primaryMuscles: ['lower back', 'spinal erectors'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['other'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your lower back and glutes controlling the descent and driving the extension, with no sharp or pinching sensation.',
    cues: [
      'Set your hip pad so you can hinge freely at the hips',
      'Lower under control until you feel a stretch through the hamstrings',
      'Extend by squeezing the glutes, not by hyperextending the lower back',
      'Stop at a straight line, do not arch past neutral',
    ],
    commonMistakes: [
      'Hyperextending past a neutral spine at the top',
      'Using momentum to snap up instead of a controlled squeeze',
      'Rounding the back on the way down',
    ],
    substitutions: ['reverse-hyper', 'romanian-deadlift'],
  },
  {
    id: 'reverse-hyper',
    name: 'Reverse Hyper',
    category: 'hypertrophy',
    primaryMuscles: ['lower back', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your glutes and lower back working to swing your legs up and back, with your lower back decompressing rather than loading under flexion.',
    cues: [
      'Rest your hips on the pad with your torso supported',
      'Swing your legs back and up using your glutes',
      'Avoid using heavy momentum to swing past control',
      'Lower under control back to the start',
    ],
    commonMistakes: [
      'Using a big swing instead of a controlled glute driven motion',
      'Hyperextending the lower back at the top',
      'Rushing the tempo instead of feeling the glutes work',
    ],
    substitutions: ['back-extension', 'romanian-deadlift'],
  },
  {
    id: 'barbell-shrug',
    name: 'Barbell Shrug',
    category: 'hypertrophy',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['forearms'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your traps pulling your shoulders straight up toward your ears, with no bend at the elbows.',
    cues: [
      'Hold the bar with straight arms in front of your thighs',
      'Elevate your shoulders straight up, not rolled forward or back',
      'Pause briefly at the top and squeeze',
      'Lower under control rather than dropping the weight',
    ],
    commonMistakes: [
      'Rolling the shoulders in a circular motion',
      'Using the elbows to help heave the weight',
      'Bouncing at the bottom instead of a controlled reset',
    ],
    substitutions: ['dumbbell-shrug'],
  },
  {
    id: 'dumbbell-shrug',
    name: 'Dumbbell Shrug',
    category: 'hypertrophy',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['forearms'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your traps pulling your shoulders straight up, with a slightly greater stretch at the bottom than a barbell shrug allows.',
    cues: [
      'Hold the dumbbells at your sides with straight arms',
      'Elevate your shoulders straight up toward your ears',
      'Pause briefly at the top and squeeze',
      'Lower slowly to feel a full stretch',
    ],
    commonMistakes: [
      'Rolling the shoulders instead of a straight vertical shrug',
      'Using momentum to bounce the weight up',
      'Cutting the stretch short at the bottom',
    ],
    substitutions: ['barbell-shrug'],
  },
  {
    id: 'band-pull-apart',
    name: 'Band Pull-Apart',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['upper back', 'rear delts'],
    secondaryMuscles: ['rotator cuff'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['band'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 15, maxReps: 25 },
    intendedFeeling:
      'You should feel your upper back and rear delts squeezing the band apart, with light, controlled tension rather than strain anywhere.',
    cues: [
      'Hold the band at shoulder height with straight arms',
      'Pull the band apart by squeezing your shoulder blades together',
      'Keep your arms roughly straight throughout',
      'Return under control rather than letting the band snap back',
    ],
    commonMistakes: [
      'Bending the elbows and turning it into a row',
      'Using a band too light to create real tension',
      'Rushing reps instead of a controlled squeeze',
    ],
    substitutions: ['face-pull', 'reverse-cable-fly'],
  },
];
