import type { CatalogExercise } from '../program-types';

/**
 * Calisthenics exercise library (R10). Preserves Scapular Push-Up, Planche
 * Lean, Scapular Pull-Up, Dead Hang, L-Sit, and Pseudo-Planche Push-Up from
 * the pre-R10 catalog verbatim (name/category/muscles/progression/guidance
 * untouched), adding only muscleGroup, equipment, and defaultPrescription.
 * Every other entry is new library content: pushing and pulling static-hold
 * skills, dip and push-up progressions, and the two qualitative warm-up
 * blocks the paste-format program references by name (Pulling Preparation,
 * Upper Body Preparation) plus the L-Sit Practice preset.
 */
export const CALISTHENICS_EXERCISES: CatalogExercise[] = [
  // --- Preserved: scapular and planche foundation ---
  {
    id: 'scapular-push-up',
    name: 'Scapular Push-Up',
    category: 'calisthenics',
    primaryMuscles: ['serratus anterior', 'scapular stabilizers'],
    secondaryMuscles: ['shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel this between and under your shoulder blades as they spread apart and pull back together, not in your arms or chest.',
    cues: [
      'Keep elbows locked straight throughout',
      'Let your shoulder blades do all the moving',
      'Push the floor away until your upper back rounds',
      'Pull shoulder blades together at the bottom without bending elbows',
    ],
    commonMistakes: [
      'Bending the elbows turns it into a mini push up',
      'Moving too fast to feel the shoulder blades work',
      'Shrugging the shoulders up toward the ears',
    ],
  },
  {
    id: 'planche-lean',
    name: 'Planche Lean',
    category: 'calisthenics',
    primaryMuscles: ['shoulders', 'chest', 'core'],
    secondaryMuscles: ['wrists', 'triceps'],
    progressionType: 'progression-chain',
    progressionChainId: 'planche-progression',
    muscleGroup: 'shoulders',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'hold', sets: 4, minSeconds: 10, maxSeconds: 20 },
    intendedFeeling:
      'You should feel constant tension through your shoulders and upper chest as they support your bodyweight, with your core braced to hold a slight posterior pelvic tilt.',
    cues: [
      'Lock your elbows and keep them locked the entire hold',
      'Actively push your shoulder blades away from each other',
      'Tuck your pelvis under slightly and squeeze your glutes',
      'Lean only as far forward as you can hold with control',
    ],
    commonMistakes: [
      'Letting the elbows bend under load',
      'Allowing the lower back to sag or arch',
      'Leaning further forward than current strength allows just to chase a number',
    ],
  },
  {
    id: 'scapular-pull-up',
    name: 'Scapular Pull-Up',
    category: 'calisthenics',
    primaryMuscles: ['scapular stabilizers', 'lats'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['bodyweight', 'pull-up-bar'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your shoulder blades doing the work as they pull down and together, with your arms staying essentially straight.',
    cues: [
      'Hang with arms straight from the bar',
      'Pull your shoulder blades down and together without bending your elbows',
      'Let your body rise slightly from the scapular movement alone',
      'Lower under control back to a full hang',
    ],
    commonMistakes: [
      'Bending the elbows and turning it into a small pull up',
      'Moving too fast to feel the shoulder blades work',
      'Shrugging up toward the ears instead of pulling down',
    ],
  },
  {
    id: 'dead-hang',
    name: 'Dead Hang',
    category: 'calisthenics',
    primaryMuscles: ['forearms', 'grip'],
    secondaryMuscles: ['lats', 'shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['bodyweight', 'pull-up-bar'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 20, maxSeconds: 40 },
    intendedFeeling:
      'You should feel your grip and forearms working to hold on, with a light stretch through your lats and shoulders.',
    cues: [
      'Hang with a relaxed but full grip on the bar',
      'Let your shoulders stretch, but keep them gently engaged, not fully collapsed',
      'Breathe steadily throughout the hold',
      'Build hang time gradually rather than forcing a longer hold',
    ],
    commonMistakes: [
      'Fully collapsing the shoulders into the joint',
      'Holding the breath instead of breathing through it',
      'Chasing a longer time than the grip can control',
    ],
  },
  {
    id: 'l-sit',
    name: 'L-Sit',
    category: 'calisthenics',
    primaryMuscles: ['hip flexors', 'core'],
    secondaryMuscles: ['shoulders', 'triceps'],
    progressionType: 'progression-chain',
    progressionChainId: 'l-sit-progression',
    muscleGroup: 'core',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 10, maxSeconds: 20 },
    intendedFeeling:
      'You should feel your core and hip flexors holding your legs up while your shoulders stay depressed and compressed, not shrugged toward your ears.',
    cues: [
      'Push down hard through your hands to depress your shoulders',
      'Keep your shoulder blades pulled down, away from your ears',
      'Brace your abs and keep a posterior pelvic tilt',
      'Work the easiest progression that still challenges the hold, and progress only when it is controlled',
    ],
    commonMistakes: [
      'Shrugging the shoulders up instead of depressing them',
      'Letting the lower back arch to help lift the legs',
      'Jumping to a harder progression before the current one is controlled',
    ],
  },
  {
    id: 'pseudo-planche-push-up',
    name: 'Pseudo-Planche Push-Up',
    category: 'calisthenics',
    primaryMuscles: ['chest', 'shoulders'],
    secondaryMuscles: ['triceps', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 5, maxReps: 10 },
    intendedFeeling:
      'You should feel your chest and shoulders taking on extra load as your hands sit back near your hips, with your core braced throughout.',
    cues: [
      'Position your hands back near your hip line, fingers pointing toward your feet',
      'Lean your shoulders forward past your hands',
      'Keep your core braced and body in a straight line',
      'Lower under control and press back up without losing the lean',
    ],
    commonMistakes: [
      'Not leaning forward enough to load the chest and shoulders',
      'Letting the hips sag instead of staying braced',
      'Flaring the elbows out wide instead of keeping them controlled',
    ],
  },

  // --- Qualitative warm-up blocks and skill practice presets ---
  {
    id: 'upper-body-preparation',
    name: 'Upper Body Preparation',
    category: 'calisthenics',
    primaryMuscles: ['wrists', 'shoulders', 'scapular stabilizers'],
    secondaryMuscles: [],
    progressionType: 'none',
    muscleGroup: 'shoulders',
    equipment: ['bodyweight', 'band'],
    defaultPrescription: {
      type: 'qualitative',
      description: 'Prepare wrists, shoulders, and scapulae for pressing work.',
      items: ['Wrist circles', 'Arm circles', 'Band pull-aparts', 'Scapular push-ups'],
      approxMinMinutes: 6,
      approxMaxMinutes: 8,
    },
    intendedFeeling:
      'You should feel your wrists, shoulders, and upper back warming up and loosening, with blood moving into the joints you are about to load.',
    cues: [
      'Move through each drill at an easy, controlled pace',
      'Cover wrists, shoulders, and shoulder blades before pressing anything heavy',
      'Use the same range of motion you will train in the workout',
      'Stop once the joints feel warm and mobile, do not force extra range',
    ],
    commonMistakes: [
      'Rushing through so fast the joints never actually warm up',
      'Skipping straight to loaded pressing without the wrist and scapular work',
      'Treating it as a stretch to hold instead of gentle repeated motion',
    ],
  },
  {
    id: 'pulling-preparation',
    name: 'Pulling Preparation',
    category: 'calisthenics',
    primaryMuscles: ['scapular stabilizers', 'upper back'],
    secondaryMuscles: ['forearms', 'grip'],
    progressionType: 'none',
    muscleGroup: 'back',
    equipment: ['bodyweight', 'band', 'pull-up-bar'],
    defaultPrescription: {
      type: 'qualitative',
      description: 'Prepare shoulders, scapulae, and upper back for pulling without creating fatigue.',
      items: ['Scapular pull-ups', 'Dead hangs', 'Band pull-aparts'],
      approxMinMinutes: 5,
      approxMaxMinutes: 7,
    },
    intendedFeeling:
      'You should feel your shoulder blades and upper back waking up and your grip settling in, without any real fatigue before the working sets.',
    cues: [
      'Keep every rep light and easy, this is preparation, not a set',
      'Let the scapular pull-ups and hangs prime the same pattern you will pull with',
      'Move at a relaxed pace through the band pull-aparts',
      'Stop as soon as the shoulders and back feel ready, do not linger',
    ],
    commonMistakes: [
      'Doing enough volume that it becomes its own fatiguing set',
      'Skipping the dead hang and going straight into loaded pulling',
      'Rushing the band pull-aparts with momentum instead of a controlled squeeze',
    ],
  },
  {
    id: 'l-sit-practice',
    name: 'L-Sit Practice',
    category: 'calisthenics',
    primaryMuscles: ['hip flexors', 'core'],
    secondaryMuscles: ['shoulders', 'triceps'],
    progressionType: 'none',
    muscleGroup: 'core',
    equipment: ['bodyweight'],
    defaultPrescription: {
      type: 'qualitative',
      description: 'Four to five high quality attempts using the hardest progression that can be held with good position.',
      approxMinMinutes: 8,
      approxMaxMinutes: 12,
    },
    intendedFeeling:
      'You should feel your hip flexors and core holding a clean, compressed position with your shoulders depressed, never a shaky, collapsing attempt.',
    cues: [
      'Pick the hardest progression you can hold with good position, not the hardest one you can barely start',
      'Depress your shoulders away from your ears before lifting your legs',
      'Prioritize a clean hold over a longer, deteriorating one',
      'Rest fully between attempts so every attempt starts fresh',
    ],
    commonMistakes: [
      'Choosing a progression too advanced and shaking through it',
      'Letting the hold continue well after position has broken down',
      'Rushing between attempts without enough recovery',
    ],
  },

  // --- Planche family ---
  {
    id: 'tuck-planche',
    name: 'Tuck Planche',
    category: 'calisthenics',
    primaryMuscles: ['shoulders', 'chest', 'core'],
    secondaryMuscles: ['wrists', 'triceps'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['bodyweight', 'parallettes'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 8, maxSeconds: 15 },
    intendedFeeling:
      'You should feel your shoulders and chest supporting your full bodyweight with your hips tucked tight, not your wrists or lower back straining.',
    cues: [
      'Round your knees and hips in tight to your chest',
      'Push the floor away and protract your shoulder blades hard',
      'Keep your elbows locked throughout the hold',
      'Lean forward only as far as you can hold without your shoulders collapsing',
    ],
    commonMistakes: [
      'Keeping the tuck too open, which shifts too much weight forward too soon',
      'Letting the elbows bend under the load',
      'Holding the breath instead of breathing through the position',
    ],
    substitutions: ['planche-lean'],
  },
  {
    id: 'advanced-tuck-planche',
    name: 'Advanced Tuck Planche',
    category: 'calisthenics',
    primaryMuscles: ['shoulders', 'chest', 'core'],
    secondaryMuscles: ['wrists', 'triceps'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['bodyweight', 'parallettes'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 5, maxSeconds: 12 },
    intendedFeeling:
      'You should feel significantly more shoulder and chest loading than a basic tuck as your hips open and your center of mass shifts forward.',
    cues: [
      'Extend your hips further open than a basic tuck while keeping knees bent',
      'Keep pushing the floor away and protracting hard',
      'Lock your elbows and resist any bend under the added load',
      'Only progress the hip angle once the current position is fully controlled',
    ],
    commonMistakes: [
      'Opening the hips faster than shoulder strength allows',
      'Letting the shoulders round forward into the ears instead of staying depressed',
      'Sacrificing elbow lockout to hold the position longer',
    ],
    substitutions: ['tuck-planche'],
  },
  {
    id: 'planche-push-up',
    name: 'Planche Push-Up',
    category: 'calisthenics',
    primaryMuscles: ['chest', 'shoulders'],
    secondaryMuscles: ['triceps', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['bodyweight', 'parallettes'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 3, maxReps: 6 },
    intendedFeeling:
      'You should feel your chest and shoulders driving the press from a forward leaning, hands back position, with your core staying rigid throughout.',
    cues: [
      'Start from the deepest tuck or straddle planche position you can control',
      'Keep your body rigid from shoulders to feet',
      'Press through a full range without letting the hips sag',
      'Only add reps once every rep keeps the same lean and body line',
    ],
    commonMistakes: [
      'Losing the forward lean partway through the press',
      'Letting the hips drop and turning it into a regular push up',
      'Cutting the range short to complete more reps',
    ],
    substitutions: ['pseudo-planche-push-up'],
  },

  // --- Pressing to handstand ---
  {
    id: 'pike-push-up',
    name: 'Pike Push-Up',
    category: 'calisthenics',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'upper chest'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your shoulders pressing your torso up between your hands, with the top of your head aiming toward the floor.',
    cues: [
      'Set your hips high so your torso is close to vertical',
      'Lower until the top of your head nearly touches the floor',
      'Press through your hands to straighten your arms',
      'Keep your neck relaxed rather than jamming your head down',
    ],
    commonMistakes: [
      'Keeping the hips too low, which turns it into a regular push up',
      'Only using a short partial range',
      'Flaring the elbows out wide instead of tracking them forward',
    ],
    substitutions: ['elevated-pike-push-up'],
  },
  {
    id: 'elevated-pike-push-up',
    name: 'Elevated Pike Push-Up',
    category: 'calisthenics',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'upper chest'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['bodyweight', 'box'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 10 },
    intendedFeeling:
      'You should feel more shoulder loading than a floor pike push up as your feet sit higher and your torso moves closer to vertical.',
    cues: [
      'Set feet on a box high enough that your torso approaches vertical',
      'Lower your head toward the floor between your hands under control',
      'Keep your core braced so your lower back does not sag',
      'Press back to a full lockout without shrugging',
    ],
    commonMistakes: [
      'Choosing a box too high before the floor version is controlled',
      'Letting the hips sag out of the pike position',
      'Rushing the descent instead of controlling it',
    ],
    substitutions: ['pike-push-up', 'wall-handstand-hold'],
  },
  {
    id: 'wall-handstand-hold',
    name: 'Wall Handstand Hold',
    category: 'calisthenics',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'core', 'wrists'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 20, maxSeconds: 45 },
    intendedFeeling:
      'You should feel your shoulders and core working together to keep a tall, straight line, with your wrists and fingers actively gripping the floor.',
    cues: [
      'Stack shoulders over wrists and keep your body in one straight line',
      'Press actively through your fingertips to fine tune balance',
      'Brace your core so your lower back does not arch',
      'Build hold time gradually rather than forcing a shaky maximum',
    ],
    commonMistakes: [
      'Letting the lower back arch heavily against the wall',
      'Holding the breath instead of breathing steadily',
      'Chasing time past the point where the position is falling apart',
    ],
    substitutions: ['handstand-push-up-wall'],
  },
  {
    id: 'handstand-push-up-wall',
    name: 'Handstand Push-Up (Wall)',
    category: 'calisthenics',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'upper chest'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 3, maxReps: 8 },
    intendedFeeling:
      'You should feel your shoulders and triceps pressing your whole bodyweight overhead, with your core staying rigid to keep the line straight.',
    cues: [
      'Set up in a stable wall handstand before starting reps',
      'Lower your head toward the floor under full control',
      'Press back up through a full range without arching the back',
      'Reduce range of motion first if full reps are not yet controlled',
    ],
    commonMistakes: [
      'Kipping or bouncing out of the bottom instead of pressing',
      'Letting the lower back arch to complete the rep',
      'Attempting full range before a controlled partial range is solid',
    ],
    substitutions: ['wall-handstand-hold'],
  },

  // --- Dips ---
  {
    id: 'ring-dip',
    name: 'Ring Dip',
    category: 'calisthenics',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['rings'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 5, maxReps: 10 },
    intendedFeeling:
      'You should feel your chest and triceps controlling both the descent and the drive up, with your shoulders staying stable against the rings drifting apart.',
    cues: [
      'Turn the rings out slightly and keep them close to your body',
      'Lower under control to a comfortable chest stretch',
      'Keep your shoulders pressed down away from your ears',
      'Press up while resisting the rings pulling your arms apart',
    ],
    commonMistakes: [
      'Descending too fast and losing ring stability',
      'Flaring the elbows out wide, straining the shoulders',
      'Cutting the range short to avoid the harder bottom position',
    ],
    substitutions: ['straight-bar-dip'],
  },
  {
    id: 'straight-bar-dip',
    name: 'Straight Bar Dip',
    category: 'calisthenics',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['dip-bars'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 12 },
    intendedFeeling:
      'You should feel your chest and triceps pressing your body back up from a deep, controlled stretch, with a slight forward lean loading the chest.',
    cues: [
      'Lean your torso forward slightly to bias the chest',
      'Lower until you feel a full stretch across the chest and shoulders',
      'Keep your elbows tracking back, not flared wide',
      'Press up to a full lockout without shrugging',
    ],
    commonMistakes: [
      'Staying too upright, which shifts load mostly to the triceps',
      'Only using a short partial range',
      'Letting the shoulders roll forward at the bottom',
    ],
    substitutions: ['ring-dip'],
  },

  // --- Front lever family ---
  {
    id: 'tuck-front-lever',
    name: 'Tuck Front Lever',
    category: 'calisthenics',
    primaryMuscles: ['lats', 'core'],
    secondaryMuscles: ['upper back', 'forearms'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['bodyweight', 'pull-up-bar'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 8, maxSeconds: 15 },
    intendedFeeling:
      'You should feel your lats and core bracing hard to keep your torso horizontal, with your arms staying straight rather than pulling like a row.',
    cues: [
      'Pull your shoulder blades down and back before lifting your hips',
      'Round your knees and hips in tight to your chest',
      'Keep your arms locked straight throughout',
      'Brace your core so your hips do not sag below your shoulder line',
    ],
    commonMistakes: [
      'Bending the elbows and turning it into a bent arm row',
      'Letting the hips sag below horizontal',
      'Holding the breath instead of breathing through the hold',
    ],
    substitutions: ['advanced-tuck-front-lever'],
  },
  {
    id: 'advanced-tuck-front-lever',
    name: 'Advanced Tuck Front Lever',
    category: 'calisthenics',
    primaryMuscles: ['lats', 'core'],
    secondaryMuscles: ['upper back', 'forearms'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['bodyweight', 'pull-up-bar'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 5, maxSeconds: 12 },
    intendedFeeling:
      'You should feel noticeably more lat and core loading than a basic tuck as your hips extend and your center of mass moves further from the bar.',
    cues: [
      'Extend your hips further open than a basic tuck while keeping knees bent',
      'Keep your shoulder blades pulled down and back',
      'Lock your arms straight and resist any bend',
      'Only open the hip angle further once the current position is controlled',
    ],
    commonMistakes: [
      'Opening the hips faster than back and core strength allows',
      'Letting the shoulders round forward instead of staying set',
      'Rushing straight to a straddle or full lever before this is solid',
    ],
    substitutions: ['tuck-front-lever'],
  },
  {
    id: 'front-lever-row',
    name: 'Front Lever Row',
    category: 'calisthenics',
    primaryMuscles: ['lats', 'upper back'],
    secondaryMuscles: ['core', 'biceps'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['bodyweight', 'pull-up-bar'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 4, maxReps: 8 },
    intendedFeeling:
      'You should feel your lats and upper back pulling your chest toward the bar while your body stays horizontal and rigid throughout the row.',
    cues: [
      'Set the lever position you can control before starting the row',
      'Pull your chest toward the bar while keeping your body straight',
      'Keep your hips from dropping as you pull',
      'Lower back to a full lever position under control',
    ],
    commonMistakes: [
      'Letting the hips drop or pike during the pull',
      'Choosing a lever angle too advanced to hold the line',
      'Yanking with the arms instead of pulling with the back',
    ],
  },
  {
    id: 'skin-the-cat',
    name: 'Skin the Cat',
    category: 'calisthenics',
    primaryMuscles: ['lats', 'shoulders'],
    secondaryMuscles: ['core', 'forearms'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['rings'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 3, maxReps: 6 },
    intendedFeeling:
      'You should feel a controlled stretch through your shoulders and lats as your body rotates through, with your core keeping the movement smooth rather than swinging.',
    cues: [
      'Start from a dead hang with straight arms',
      'Tuck your knees and roll through slowly, keeping the rings close',
      'Control the shoulder stretch at the bottom rather than dropping into it',
      'Reverse the movement back to the hang with the same control',
    ],
    commonMistakes: [
      'Swinging into the rotation instead of moving under control',
      'Forcing more shoulder range than currently available',
      'Rushing the return and losing tension in the rings',
    ],
  },
  {
    id: 'muscle-up-bar',
    name: 'Muscle-Up (Bar)',
    category: 'calisthenics',
    primaryMuscles: ['lats', 'chest'],
    secondaryMuscles: ['triceps', 'biceps', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['bodyweight', 'pull-up-bar'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 2, maxReps: 5 },
    intendedFeeling:
      'You should feel a powerful pull that transitions smoothly into a press, with your lats driving the pull and your chest and triceps finishing the transition.',
    cues: [
      'Pull explosively and aim your chest toward the bar, not just your chin',
      'Lead the transition with your chest rolling over the bar',
      'Keep the transition close to the bar rather than swinging away from it',
      'Finish with a controlled press to full lockout',
    ],
    commonMistakes: [
      'Relying on a big kip instead of pulling strength for the transition',
      'Pulling straight up like a pull up with no chest lean into the bar',
      'Banging the wrists and forearms into the bar during the transition',
    ],
    substitutions: ['pull-up'],
  },
  {
    id: 'archer-pull-up',
    name: 'Archer Pull-Up',
    category: 'calisthenics',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper back'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['bodyweight', 'pull-up-bar'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 3, maxReps: 6, perSide: true },
    intendedFeeling:
      'You should feel one side pulling almost all the bodyweight while the other arm stays extended for balance, loading that lat much harder than a normal pull up.',
    cues: [
      'Pull toward one hand while keeping the other arm extended out to the side',
      'Drive the pulling elbow down and back',
      'Keep the extended arm active rather than completely passive',
      'Lower under control back to a full hang before switching sides',
    ],
    commonMistakes: [
      'Letting the extended arm do meaningful pulling work',
      'Twisting the torso instead of pulling straight to one side',
      'Choosing this before strict pull ups are controlled for reps',
    ],
    substitutions: ['typewriter-pull-up'],
  },
  {
    id: 'typewriter-pull-up',
    name: 'Typewriter Pull-Up',
    category: 'calisthenics',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper back'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['bodyweight', 'pull-up-bar'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 4, maxReps: 8, perSide: true },
    intendedFeeling:
      'You should feel your lats working unilaterally as you shift your chin from one hand to the other while staying up near the bar.',
    cues: [
      'Pull to the top of a normal pull up before shifting side to side',
      'Keep your chin near the bar throughout the entire shift',
      'Shift slowly and under control rather than bouncing across',
      'Lower fully only after returning to center',
    ],
    commonMistakes: [
      'Dropping height while shifting side to side',
      'Rushing the shift and losing control near the bar',
      'Using momentum from the hips to swing across',
    ],
    substitutions: ['archer-pull-up'],
  },

  // --- Push-up progressions ---
  {
    id: 'ring-push-up',
    name: 'Ring Push-Up',
    category: 'calisthenics',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['rings'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 15 },
    intendedFeeling:
      'You should feel your chest and shoulders working through a deeper stretch than a floor push up, with your core and stabilizers fighting to keep the rings steady.',
    cues: [
      'Keep the rings turned out slightly through the full range',
      'Lower until you feel a deep, controlled stretch across the chest',
      'Keep your body in one straight line from shoulders to feet',
      'Press up while resisting the rings drifting apart or together',
    ],
    commonMistakes: [
      'Letting the hips sag out of a straight body line',
      'Losing control of the rings and letting them wobble excessively',
      'Cutting the range short to avoid instability',
    ],
    substitutions: ['archer-push-up'],
  },
  {
    id: 'archer-push-up',
    name: 'Archer Push-Up',
    category: 'calisthenics',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 4, maxReps: 8, perSide: true },
    intendedFeeling:
      'You should feel one side of your chest and shoulder taking on most of the load while the other arm stays extended for balance.',
    cues: [
      'Take a wide hand position and shift your weight toward one side',
      'Keep the extended arm mostly straight for support, not pressing',
      'Lower your chest toward the working hand under control',
      'Press back up and shift toward the other side for the next rep',
    ],
    commonMistakes: [
      'Letting the extended arm do meaningful pressing work',
      'Only lowering part way instead of a full stretch on the working side',
      'Rotating the torso instead of shifting weight cleanly side to side',
    ],
    substitutions: ['one-arm-push-up-progression', 'ring-push-up'],
  },
  {
    id: 'one-arm-push-up-progression',
    name: 'One-Arm Push-Up Progression',
    category: 'calisthenics',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps', 'core', 'obliques'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 3, maxReps: 6, perSide: true },
    intendedFeeling:
      'You should feel your chest, shoulder, and core on the working side bracing hard against the rotational pull of pressing with one arm.',
    cues: [
      'Set a wide foot stance for a stable base',
      'Brace your core hard to resist rotating toward the floor',
      'Lower under full control to a comfortable, controlled depth',
      'Use the easiest variation, such as an incline, that still challenges the working side',
    ],
    commonMistakes: [
      'Letting the hips and torso rotate to help the press',
      'Choosing too steep an angle before the current level is controlled',
      'Dropping into the bottom instead of lowering under control',
    ],
    substitutions: ['archer-push-up'],
  },

  // --- L-sit and static holds ---
  {
    id: 'tuck-l-sit',
    name: 'Tuck L-Sit',
    category: 'calisthenics',
    primaryMuscles: ['hip flexors', 'core'],
    secondaryMuscles: ['shoulders', 'triceps'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['bodyweight', 'parallettes'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 10, maxSeconds: 20 },
    intendedFeeling:
      'You should feel your core holding your knees up close to your chest while your shoulders stay depressed and your arms support the hold.',
    cues: [
      'Push down through your hands to depress your shoulders',
      'Pull your knees in tight toward your chest',
      'Keep your lower back from rounding excessively',
      'Breathe steadily rather than holding your breath through the hold',
    ],
    commonMistakes: [
      'Shrugging the shoulders up toward the ears',
      'Letting the knees drift away from the chest as fatigue sets in',
      'Rushing to extend the legs before the tuck is solid',
    ],
    substitutions: ['one-leg-l-sit', 'l-sit'],
  },
  {
    id: 'one-leg-l-sit',
    name: 'One-Leg L-Sit',
    category: 'calisthenics',
    primaryMuscles: ['hip flexors', 'core'],
    secondaryMuscles: ['shoulders', 'triceps'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['bodyweight', 'parallettes'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 8, maxSeconds: 18 },
    intendedFeeling:
      'You should feel one leg extended and one leg tucked, with your core working harder on the extended side to keep both legs at the same height.',
    cues: [
      'Extend one leg fully while keeping the other tucked in',
      'Keep both legs at roughly the same height',
      'Push down hard through your hands and keep shoulders depressed',
      'Switch which leg extends between sets to train both sides evenly',
    ],
    commonMistakes: [
      'Letting the extended leg drop lower than the tucked one',
      'Rounding the lower back to help lift the extended leg',
      'Only ever practicing with the same leg extended',
    ],
    substitutions: ['tuck-l-sit', 'v-sit'],
  },
  {
    id: 'v-sit',
    name: 'V-Sit',
    category: 'calisthenics',
    primaryMuscles: ['hip flexors', 'core'],
    secondaryMuscles: ['shoulders', 'hamstrings'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['bodyweight', 'parallettes'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 5, maxSeconds: 12 },
    intendedFeeling:
      'You should feel your hip flexors and core working hard to lift both legs well above horizontal while your shoulders stay depressed and supporting.',
    cues: [
      'Raise both legs together well above hip height',
      'Keep your torso as upright as your hip flexibility allows',
      'Push down through your hands and keep shoulders depressed',
      'Only attempt this once a full L-sit is comfortably controlled',
    ],
    commonMistakes: [
      'Leaning the torso back excessively to lift the legs higher',
      'Attempting this before a full L-sit is solid',
      'Letting the shoulders creep up toward the ears under fatigue',
    ],
    substitutions: ['l-sit'],
  },

  // --- Support holds ---
  {
    id: 'ring-support-hold',
    name: 'Ring Support Hold',
    category: 'calisthenics',
    primaryMuscles: ['shoulders', 'chest'],
    secondaryMuscles: ['triceps', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['rings'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 15, maxSeconds: 30 },
    intendedFeeling:
      'You should feel your shoulders and chest actively pressing the rings down and slightly in, resisting the rings drifting apart, rather than just locking your elbows and hanging.',
    cues: [
      'Turn the rings out and press them down and slightly together',
      'Keep your shoulders depressed away from your ears',
      'Keep a slight hollow body position through your torso',
      'Lock your elbows without over-extending them',
    ],
    commonMistakes: [
      'Letting the rings drift apart and the shoulders roll forward',
      'Passively hanging on locked elbows instead of actively pressing',
      'Losing the hollow position and letting the hips sag',
    ],
    substitutions: ['parallette-support-hold'],
  },
  {
    id: 'parallette-support-hold',
    name: 'Parallette Support Hold',
    category: 'calisthenics',
    primaryMuscles: ['shoulders', 'chest'],
    secondaryMuscles: ['triceps', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['parallettes'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 15, maxSeconds: 30 },
    intendedFeeling:
      'You should feel your shoulders and triceps actively supporting your bodyweight, with your shoulder blades depressed rather than shrugged up.',
    cues: [
      'Press down actively into the parallettes rather than just resting on locked elbows',
      'Depress your shoulder blades down away from your ears',
      'Keep a slight forward lean and hollow torso position',
      'Build hold time gradually rather than forcing a shaky maximum',
    ],
    commonMistakes: [
      'Shrugging the shoulders up under fatigue',
      'Letting the hips sag out of the hollow position',
      'Locking out passively instead of pressing down actively',
    ],
    substitutions: ['ring-support-hold'],
  },

  // --- Rows and pulling variations ---
  {
    id: 'bodyweight-row-feet-elevated',
    name: 'Bodyweight Row (Feet Elevated)',
    category: 'calisthenics',
    primaryMuscles: ['upper back', 'lats'],
    secondaryMuscles: ['biceps', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['bodyweight', 'pull-up-bar', 'box'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 15 },
    intendedFeeling:
      'You should feel your upper back and lats pulling your chest to the bar against a heavier bodyweight lean than a standard row, with your core bracing to keep a straight line.',
    cues: [
      'Set your feet on an elevated surface so your body angle is closer to horizontal',
      'Pull your chest toward the bar, driving elbows back',
      'Keep your body rigid in a straight line from shoulders to heels',
      'Lower under control to a full stretch before the next rep',
    ],
    commonMistakes: [
      'Letting the hips sag or pike during the pull',
      'Yanking with the arms instead of pulling with the back',
      'Choosing a body angle too horizontal before that range is controlled',
    ],
  },
];
