import type { CatalogExercise } from '../program-types';

// Calf and lower-leg work: standing and seated calf raise variants plus
// tibialis anterior, the shin muscle that balances calf-dominant training.

export const CALF_EXERCISES: CatalogExercise[] = [
  {
    id: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    category: 'hypertrophy',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'calves',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your calves stretch fully at the bottom and squeeze hard at the top of every rep.',
    cues: [
      'Lower your heels until you feel a full stretch',
      'Rise as high onto your toes as possible',
      'Pause briefly at the top and squeeze',
      'Control the descent rather than dropping down',
    ],
    commonMistakes: [
      'Bouncing at the bottom instead of pausing',
      'Only using a short partial range',
      'Rushing reps so momentum replaces the calf squeeze',
    ],
    substitutions: ['calf-raise', 'smith-machine-calf-raise'],
  },
  {
    id: 'calf-raise',
    name: 'Calf Raise',
    category: 'hypertrophy',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'calves',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your calves stretch at the bottom and squeeze fully at the top of every rep.',
    cues: [
      'Lower your heels until you feel a full stretch',
      'Push up as high onto your toes as possible',
      'Pause and squeeze at the top',
      'Control the descent instead of dropping',
    ],
    commonMistakes: [
      'Bouncing out of the bottom stretch',
      'Using a short, partial range',
      'Rushing reps so the calf never fully contracts',
    ],
    substitutions: ['standing-calf-raise', 'seated-calf-raise'],
  },
  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    category: 'hypertrophy',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['soleus'],
    progressionType: 'double-progression',
    muscleGroup: 'calves',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20 },
    intendedFeeling:
      'You should feel the load shift deeper into your soleus with your knees bent, stretching and squeezing through a full range.',
    cues: [
      'Set the pad snug across your lower thighs',
      'Lower your heels until you feel a full stretch',
      'Rise as high onto your toes as possible',
      'Pause briefly at the top before lowering under control',
    ],
    commonMistakes: [
      'Only working a short partial range',
      'Bouncing at the bottom of the stretch',
      'Letting the knees lift off the pad to cheat more height',
    ],
    substitutions: ['standing-calf-raise', 'calf-raise'],
  },
  {
    id: 'leg-press-calf-raise',
    name: 'Leg Press Calf Raise',
    category: 'hypertrophy',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'calves',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 15 },
    intendedFeeling:
      'You should feel your calves working through a full range with your legs almost straight, using the sled as resistance instead of your bodyweight.',
    cues: [
      'Set your legs nearly straight with the balls of your feet on the platform edge',
      'Lower your heels until you feel a full stretch',
      'Press up onto your toes as high as possible',
      'Control the descent rather than letting the sled drop',
    ],
    commonMistakes: [
      'Keeping the knees bent, which shifts load off the calves',
      'Only using a short partial range',
      'Letting the sled bounce at the bottom',
    ],
    substitutions: ['standing-calf-raise'],
  },
  {
    id: 'single-leg-calf-raise',
    name: 'Single-Leg Calf Raise',
    category: 'hypertrophy',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'calves',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15, perSide: true },
    intendedFeeling:
      'You should feel one calf carrying your full bodyweight through the whole range, without the other leg helping.',
    cues: [
      'Hold something stable for balance if needed',
      'Lower your heel until you feel a full stretch',
      'Rise as high onto your toes as you can control',
      'Lower slowly rather than dropping down',
    ],
    commonMistakes: [
      'Letting the resting foot take some of the load',
      'Rushing reps instead of controlling the stretch and squeeze',
      'Using a short, partial range to move faster',
    ],
    substitutions: ['standing-calf-raise', 'donkey-calf-raise'],
  },
  {
    id: 'donkey-calf-raise',
    name: 'Donkey Calf Raise',
    category: 'hypertrophy',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'calves',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 15 },
    intendedFeeling:
      'You should feel an especially deep calf stretch from the forward-hinged position, with a strong squeeze at the top of each rep.',
    cues: [
      'Hinge forward at the hips with your torso supported',
      'Lower your heels until you feel a full stretch',
      'Rise onto your toes as high as possible',
      'Pause and squeeze at the top before lowering under control',
    ],
    commonMistakes: [
      'Standing too upright, which shortens the stretch',
      'Bouncing out of the bottom instead of pausing',
      'Only working the top half of the range',
    ],
    substitutions: ['standing-calf-raise', 'seated-calf-raise'],
  },
  {
    id: 'smith-machine-calf-raise',
    name: 'Smith Machine Calf Raise',
    category: 'hypertrophy',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'calves',
    equipment: ['smith-machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel the same full calf stretch and squeeze as a standing machine raise, from a fixed bar path.',
    cues: [
      'Set the balls of your feet on a small platform or plate',
      'Lower your heels until you feel a full stretch',
      'Rise as high onto your toes as possible',
      'Control the descent rather than dropping down',
    ],
    commonMistakes: [
      'Only using a short partial range',
      'Bouncing at the bottom of the stretch',
      'Letting the knees bend to assist the raise',
    ],
    substitutions: ['standing-calf-raise', 'calf-raise'],
  },
  {
    id: 'tibialis-raise',
    name: 'Tibialis Raise',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['tibialis anterior'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'calves',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 15, maxReps: 20 },
    intendedFeeling:
      'You should feel the front of your shin working as your toes pull up toward your knee.',
    cues: [
      'Keep your heel planted and pull your toes up',
      'Move through a full range you can control',
      'Pause briefly at the top of each rep',
      'Lower slowly rather than letting the foot drop',
    ],
    commonMistakes: [
      'Using only a small, rushed range of motion',
      'Letting the heel roll or lift off the ground',
      'Moving too fast to control the lowering phase',
    ],
  },
];
