import type { CatalogExercise } from '../program-types';

/**
 * Chest exercise library (R10). Preserves Incline Dumbbell Press and Cable
 * Fly from the pre-R10 catalog verbatim (name/category/muscles/progression/
 * guidance untouched), adding only muscleGroup, equipment, and
 * defaultPrescription. Every other entry is new library content.
 */
export const CHEST_EXERCISES: CatalogExercise[] = [
  // --- Barbell presses ---
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['barbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 10 },
    intendedFeeling:
      'You should feel your chest driving the bar off your sternum, with your shoulders and triceps finishing the lockout, not initiating it.',
    cues: [
      'Set your shoulder blades back and down before unracking',
      'Lower the bar to your lower sternum under control',
      'Keep your wrists stacked directly over your elbows',
      'Drive the bar up and slightly back toward your face',
    ],
    commonMistakes: [
      'Flaring the elbows to 90 degrees and stressing the shoulders',
      'Bouncing the bar off the chest instead of controlling the descent',
      'Losing shoulder blade retraction partway through the set',
    ],
    substitutions: ['dumbbell-bench-press', 'machine-chest-press', 'incline-barbell-bench-press'],
  },
  {
    id: 'incline-barbell-bench-press',
    name: 'Incline Barbell Bench Press',
    category: 'strength',
    primaryMuscles: ['upper chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['barbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 10 },
    intendedFeeling:
      'You should feel the load concentrated across your upper chest, with your front delts assisting but not taking over the press.',
    cues: [
      'Set the bench to a moderate incline, not a near vertical shoulder press',
      'Lower the bar to your upper chest, just below the collarbone',
      'Keep your elbows at roughly a 45 degree angle from your torso',
      'Drive up without letting your hips rise off the bench',
    ],
    commonMistakes: [
      'Setting the incline too steep and turning it into a shoulder press',
      'Flaring the elbows out to a full 90 degrees',
      'Arching hard and lifting the hips to move more weight',
    ],
    substitutions: ['incline-dumbbell-press', 'incline-machine-press'],
  },
  {
    id: 'floor-press',
    name: 'Floor Press',
    category: 'strength',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 10 },
    intendedFeeling:
      'You should feel your chest and triceps pressing through a shortened range, with your upper arms resting briefly on the floor at the bottom.',
    cues: [
      'Let your upper arms touch the floor lightly at the bottom, do not slam down',
      'Pause briefly at the bottom before pressing',
      'Keep your feet flat and glutes on the floor throughout',
      'Press straight up without arching off the floor',
    ],
    commonMistakes: [
      'Bouncing the elbows off the floor instead of pausing',
      'Flaring the elbows wide at the bottom',
      'Using leg drive by lifting the hips off the floor',
    ],
    substitutions: ['barbell-bench-press', 'close-grip-bench-press'],
  },

  // --- Dumbbell presses ---
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    category: 'hypertrophy',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['dumbbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel a deeper stretch across your chest than a barbell press allows, with the squeeze concentrated at the top as the dumbbells come together.',
    cues: [
      'Lower the dumbbells until you feel a full stretch across the chest',
      'Keep your wrists stacked over your elbows throughout',
      'Press up and slightly inward, letting the dumbbells nearly touch',
      'Keep your shoulder blades pinned to the bench',
    ],
    commonMistakes: [
      'Letting the dumbbells drift out wide and stressing the shoulders',
      'Cutting the stretch short at the bottom',
      'Clanking the dumbbells together instead of a controlled squeeze',
    ],
    substitutions: ['barbell-bench-press', 'machine-chest-press', 'incline-dumbbell-press'],
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    category: 'hypertrophy',
    primaryMuscles: ['upper chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel the stretch and squeeze concentrated across your upper chest, with your shoulders and triceps assisting but not taking over.',
    cues: [
      'Set the bench so you feel the incline in your upper chest, not your front delts',
      'Lower the dumbbells under control until you feel a stretch across the chest',
      'Drive the dumbbells up and slightly together at the top',
      'Keep shoulder blades pulled back and down into the bench',
    ],
    commonMistakes: [
      'Flaring the elbows so the front delts take over',
      'Bouncing the dumbbells at the bottom of the stretch',
      'Pressing with an arched back to move more weight',
    ],
    muscleGroup: 'chest',
    equipment: ['dumbbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    substitutions: ['incline-barbell-bench-press', 'incline-machine-press'],
  },
  {
    id: 'decline-dumbbell-press',
    name: 'Decline Dumbbell Press',
    category: 'hypertrophy',
    primaryMuscles: ['lower chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['dumbbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel the squeeze concentrated low across your chest, with minimal shoulder involvement.',
    cues: [
      'Secure your legs and set a slight decline',
      'Lower the dumbbells to the sides of your lower chest',
      'Press up and slightly together, squeezing at the top',
      'Keep your neck relaxed against the bench',
    ],
    commonMistakes: [
      'Setting too steep a decline and losing chest tension',
      'Rushing reps because the range feels shorter',
      'Letting the dumbbells drift toward the face instead of the lower chest line',
    ],
    substitutions: ['dumbbell-bench-press', 'decline-barbell-bench-press'],
  },
  {
    id: 'decline-barbell-bench-press',
    name: 'Decline Barbell Bench Press',
    category: 'strength',
    primaryMuscles: ['lower chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['barbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 10 },
    intendedFeeling:
      'You should feel the load low across your chest with a shorter, more efficient range than a flat press.',
    cues: [
      'Lock your legs under the pads before unracking',
      'Lower the bar to your lower chest',
      'Keep your elbows tucked closer than a flat bench press',
      'Press up and slightly back toward your face',
    ],
    commonMistakes: [
      'Bouncing the bar off the chest due to the shorter range',
      'Flaring the elbows wide',
      'Losing leg lock and sliding on the bench',
    ],
    substitutions: ['decline-dumbbell-press', 'barbell-bench-press'],
  },

  // --- Machine and Smith presses ---
  {
    id: 'machine-chest-press',
    name: 'Machine Chest Press',
    category: 'hypertrophy',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your chest driving the handles through a fixed, controlled path, with no need to stabilize the weight path yourself.',
    cues: [
      'Set the seat so the handles line up with the middle of your chest',
      'Press without shrugging your shoulders up',
      'Extend fully without slamming the handles at lockout',
      'Control the return to a full stretch',
    ],
    commonMistakes: [
      'Setting the seat too low or high and losing chest tension',
      'Only using the top half of the range',
      'Shrugging the shoulders to assist the press',
    ],
    substitutions: ['dumbbell-bench-press', 'smith-machine-bench-press'],
  },
  {
    id: 'incline-machine-press',
    name: 'Incline Machine Press',
    category: 'hypertrophy',
    primaryMuscles: ['upper chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your upper chest working through a fixed incline path, with the machine controlling the bar path so you can focus on the squeeze.',
    cues: [
      'Set the seat so the handles start at upper chest height',
      'Press up without shrugging toward your ears',
      'Squeeze the upper chest at full extension',
      'Lower under control to a full stretch',
    ],
    commonMistakes: [
      'Setting the seat too low and shifting load to the front delts',
      'Using momentum to jerk the handles up',
      'Cutting the stretch short at the bottom',
    ],
    substitutions: ['incline-dumbbell-press', 'incline-barbell-bench-press'],
  },
  {
    id: 'smith-machine-bench-press',
    name: 'Smith Machine Bench Press',
    category: 'hypertrophy',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['smith-machine', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your chest pressing against a fixed vertical bar path, useful for pushing close to failure without needing a spotter.',
    cues: [
      'Position the bench so the bar lowers to your lower sternum',
      'Keep your wrists stacked under the bar throughout',
      'Unrack and re-rack with a deliberate wrist rotation',
      'Lower under control rather than letting the bar drop',
    ],
    commonMistakes: [
      'Positioning the bench wrong so the bar path does not match natural pressing angle',
      'Flaring the elbows since the bar path is fixed',
      'Forgetting to rotate and lock the bar into the rack at the end of the set',
    ],
    substitutions: ['barbell-bench-press', 'machine-chest-press'],
  },

  // --- Flyes ---
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    category: 'hypertrophy',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel a stretch and squeeze across the middle of your chest as your hands sweep together, not tension in your front delts.',
    cues: [
      'Set a slight forward lean and soft bend in the elbows',
      'Let the cables pull your arms back until you feel a stretch in the chest',
      'Bring your hands together in an arcing path, like hugging a barrel',
      'Squeeze your chest at the finish rather than just moving the handles',
    ],
    commonMistakes: [
      'Turning the arc into a straight press with the shoulders',
      'Using so much weight that the stretch gets cut short',
      'Letting the elbows lock straight and shift work to the shoulders',
    ],
    muscleGroup: 'chest',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    substitutions: ['low-to-high-cable-fly', 'high-to-low-cable-fly', 'dumbbell-fly'],
  },
  {
    id: 'low-to-high-cable-fly',
    name: 'Low to High Cable Fly',
    category: 'hypertrophy',
    primaryMuscles: ['upper chest'],
    secondaryMuscles: ['shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel the squeeze biased toward your upper chest as your hands sweep up and together in front of your face.',
    cues: [
      'Set both pulleys at the lowest position',
      'Keep a soft bend in the elbows throughout',
      'Sweep your hands up and across in front of your upper chest',
      'Squeeze at the top rather than just reaching the handles together',
    ],
    commonMistakes: [
      'Turning it into a shoulder raise instead of a chest fly',
      'Letting the elbows bend and straighten instead of staying fixed',
      'Using too much weight and losing the arc for a straight line',
    ],
    substitutions: ['cable-fly', 'high-to-low-cable-fly'],
  },
  {
    id: 'high-to-low-cable-fly',
    name: 'High to Low Cable Fly',
    category: 'hypertrophy',
    primaryMuscles: ['lower chest'],
    secondaryMuscles: ['shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel the squeeze biased toward your lower chest as your hands sweep down and together in front of your hips.',
    cues: [
      'Set both pulleys at the highest position',
      'Keep a soft bend in the elbows throughout',
      'Sweep your hands down and across toward your hips',
      'Squeeze your lower chest at the bottom of the arc',
    ],
    commonMistakes: [
      'Bending the elbows more as the set fatigues, shortening the arc',
      'Leaning the torso instead of isolating the chest',
      'Stopping the sweep short of the hips',
    ],
    substitutions: ['cable-fly', 'low-to-high-cable-fly'],
  },
  {
    id: 'dumbbell-fly',
    name: 'Dumbbell Fly',
    category: 'hypertrophy',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['dumbbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel a deep stretch across your chest at the bottom, with the squeeze happening as your arms sweep back together over your chest.',
    cues: [
      'Keep a fixed, soft bend in your elbows for the whole set',
      'Lower the dumbbells out to the sides until you feel a full stretch',
      'Sweep your arms back together in an arcing path over your chest',
      'Avoid pressing the weight up, this is a sweeping motion, not a press',
    ],
    commonMistakes: [
      'Bending the elbows more at the bottom to protect the shoulders, turning it into a press',
      'Lowering past a comfortable stretch and straining the shoulder joint',
      'Using so much weight that control is lost at the bottom',
    ],
    substitutions: ['cable-fly', 'pec-deck'],
  },
  {
    id: 'pec-deck',
    name: 'Pec Deck',
    category: 'hypertrophy',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your chest squeezing your arms together in a fixed, supported path with almost no shoulder stabilization required.',
    cues: [
      'Set the seat so the handles line up with your chest',
      'Bring your arms together in a slow, controlled squeeze',
      'Pause briefly with your arms fully together',
      'Control the return to a full stretch rather than letting the pads snap back',
    ],
    commonMistakes: [
      'Setting the seat too low or high and losing the chest line',
      'Using momentum to slam the pads together',
      'Cutting the stretch short on the return',
    ],
    substitutions: ['cable-fly', 'dumbbell-fly'],
  },

  {
    id: 'single-arm-cable-fly',
    name: 'Single-Arm Cable Fly',
    category: 'hypertrophy',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'obliques'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15, perSide: true },
    intendedFeeling:
      'You should feel one side of your chest working through a full stretch and squeeze, with your core resisting the pull of the cable toward that side.',
    cues: [
      'Stand square and brace your core against the cable pull',
      'Keep a soft, fixed bend in the working elbow',
      'Sweep your hand across your body in an arc, finishing near your opposite hip',
      'Reset square before starting the next rep',
    ],
    commonMistakes: [
      'Letting the torso rotate toward the cable to help finish the rep',
      'Losing the arc and turning it into a press',
      'Rushing the return and losing the stretch',
    ],
    substitutions: ['cable-fly', 'dumbbell-fly'],
  },
  {
    id: 'svend-press',
    name: 'Svend Press',
    category: 'hypertrophy',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['other'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20 },
    intendedFeeling:
      'You should feel constant inner chest tension from squeezing the plates together, distinct from the stretch focused feeling of a fly or press.',
    cues: [
      'Press two plates together at chest height with straight arms',
      'Keep squeezing the plates together for the entire set',
      'Press straight out until your arms are extended, then return to your chest',
      'Keep your shoulders down, away from your ears',
    ],
    commonMistakes: [
      'Letting the squeeze pressure relax between reps',
      'Shrugging the shoulders up during the press',
      'Using so much weight that the squeeze cannot be maintained',
    ],
    substitutions: ['cable-fly', 'dumbbell-fly'],
  },

  // --- Bodyweight and dips ---
  {
    id: 'push-up',
    name: 'Push-Up',
    category: 'calisthenics',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 20 },
    intendedFeeling:
      'You should feel your chest and shoulders lowering and pressing your whole body as one rigid unit, with your core preventing any sag.',
    cues: [
      'Keep a straight line from your head to your heels',
      'Lower your chest until your upper arms are about level with your torso',
      'Keep your elbows at roughly 45 degrees, not flared to 90',
      'Press the floor away rather than just straightening the arms',
    ],
    commonMistakes: [
      'Letting the hips sag or pike up',
      'Only lowering halfway',
      'Flaring the elbows out to a full 90 degrees',
    ],
    substitutions: ['deficit-push-up', 'dumbbell-bench-press'],
  },
  {
    id: 'deficit-push-up',
    name: 'Deficit Push-Up',
    category: 'calisthenics',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['bodyweight', 'parallettes'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 15 },
    intendedFeeling:
      'You should feel a deeper stretch across your chest at the bottom than a standard push up allows, since your hands are elevated on parallettes or blocks.',
    cues: [
      'Keep the same straight body line as a standard push up',
      'Lower until you feel a full stretch across the chest',
      'Keep elbows around 45 degrees, not flared',
      'Press back up through the full added range',
    ],
    commonMistakes: [
      'Lowering only to the depth of a normal push up and wasting the deficit',
      'Letting the hips sag at the bottom of the deeper range',
      'Rushing the descent instead of controlling the extra stretch',
    ],
    substitutions: ['push-up'],
  },
  {
    id: 'dip',
    name: 'Dip',
    category: 'calisthenics',
    primaryMuscles: ['lower chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'chest',
    equipment: ['dip-bars'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 15 },
    intendedFeeling:
      'You should feel your lower chest stretching at the bottom when you lean forward, with a controlled press back to lockout.',
    cues: [
      'Lean your torso forward to bias the chest over the triceps',
      'Lower until your shoulders dip just below your elbows',
      'Keep a slight forward lean throughout the rep',
      'Press up under control without swinging',
    ],
    commonMistakes: [
      'Staying upright and turning it into a triceps only movement',
      'Descending so deep it strains the front of the shoulder',
      'Using momentum from a leg kick to finish the rep',
    ],
    substitutions: ['push-up'],
  },
];
