import type { CatalogExercise } from '../program-types';

// Core and trunk work: flexion, anti-extension, anti-rotation, and
// anti-lateral-flexion patterns, plus loaded carries. Carries use
// muscleGroup 'full-body' since they load the whole body under a fixed
// posture rather than isolating the trunk, but they belong here because
// bracing the core is the point of the exercise.

export const CORE_EXERCISES: CatalogExercise[] = [
  // --- Spinal flexion ---
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    category: 'hypertrophy',
    primaryMuscles: ['rectus abdominis'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 15 },
    intendedFeeling:
      'You should feel your abs crunching and shortening through the range, not your hip flexors or shoulders pulling the weight.',
    cues: [
      'Kneel with the cable at your head or upper back',
      'Round your spine and crunch down using your abs',
      'Keep your hips still, do not sit back onto your heels',
      'Squeeze your abs hard at the bottom before returning',
    ],
    commonMistakes: [
      'Pulling with the arms instead of crunching with the abs',
      'Moving the hips back like a hip hinge rather than curling the spine',
      'Using so much weight the range gets cut short',
    ],
    substitutions: ['machine-crunch', 'v-up'],
  },
  {
    id: 'machine-crunch',
    name: 'Machine Crunch',
    category: 'hypertrophy',
    primaryMuscles: ['rectus abdominis'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 15 },
    intendedFeeling:
      'You should feel your abs contracting hard against resistance through a full crunch, with your hip flexors staying quiet.',
    cues: [
      'Set the pad against your upper chest or shoulders',
      'Curl your spine to crunch down, leading with your ribs, not your arms',
      'Squeeze your abs hard at the bottom of the rep',
      'Return under control to a full stretch',
    ],
    commonMistakes: [
      'Pulling with the arms on the handles instead of crunching with the abs',
      'Using a load heavy enough to shorten the range',
      'Rushing reps instead of pausing at the contraction',
    ],
    substitutions: ['cable-crunch'],
  },
  {
    id: 'reverse-crunch',
    name: 'Reverse Crunch',
    category: 'hypertrophy',
    primaryMuscles: ['rectus abdominis'],
    secondaryMuscles: ['hip flexors'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 15 },
    intendedFeeling:
      'You should feel your lower abs curling your hips off the floor toward your ribs, not your hip flexors swinging your legs.',
    cues: [
      'Lie on your back with your knees bent toward your chest',
      'Curl your hips up off the floor using your lower abs',
      'Keep the movement small and controlled rather than swinging your legs',
      'Lower under control instead of dropping your hips',
    ],
    commonMistakes: [
      'Swinging the legs with momentum instead of curling the hips',
      'Using the hip flexors alone without lifting the pelvis',
      'Arching the lower back to gain more swing',
    ],
  },
  {
    id: 'decline-sit-up',
    name: 'Decline Sit-Up',
    category: 'hypertrophy',
    primaryMuscles: ['rectus abdominis'],
    secondaryMuscles: ['hip flexors'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 15 },
    intendedFeeling:
      'You should feel your abs working through a longer range than a flat sit-up, with your hip flexors assisting rather than leading.',
    cues: [
      'Anchor your feet and set the bench to a manageable decline',
      'Curl your spine up one segment at a time rather than yanking upright',
      'Keep your chin tucked slightly, not straining your neck',
      'Lower under control back to a full stretch',
    ],
    commonMistakes: [
      'Using momentum to throw the torso upright',
      'Pulling on the neck instead of curling with the abs',
      'Setting the decline steeper than current strength controls',
    ],
    substitutions: ['reverse-crunch', 'v-up'],
  },
  {
    id: 'v-up',
    name: 'V-Up',
    category: 'calisthenics',
    primaryMuscles: ['rectus abdominis'],
    secondaryMuscles: ['hip flexors'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your entire ab wall folding your torso and legs together, meeting in the middle under control.',
    cues: [
      'Start lying flat with arms extended overhead',
      'Fold at the hips, bringing your hands toward your feet',
      'Keep both legs and your torso lifted off the floor',
      'Lower under control back to a full stretch',
    ],
    commonMistakes: [
      'Bending the knees heavily to make the fold easier',
      'Using momentum to rock up instead of a controlled fold',
      'Only lifting the torso without raising the legs to meet it',
    ],
  },
  {
    id: 'dragon-flag',
    name: 'Dragon Flag',
    category: 'calisthenics',
    primaryMuscles: ['rectus abdominis', 'deep core'],
    secondaryMuscles: ['lats', 'shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 4, maxReps: 8 },
    intendedFeeling:
      'You should feel your entire trunk bracing to keep your body rigid as you lower from your shoulders, with only your upper back touching the bench.',
    cues: [
      'Anchor your hands behind your head on a stable bench',
      'Keep your body in one straight, rigid line as you lower',
      'Lower only as far as you can control without your hips sagging',
      'Curl back up leading with the hips, not by kipping',
    ],
    commonMistakes: [
      'Letting the hips sag or bend during the lower',
      'Lowering faster than the core can control',
      'Using the arms to yank the body back up',
    ],
  },
  {
    id: 'hollow-body-rock',
    name: 'Hollow Body Rock',
    category: 'calisthenics',
    primaryMuscles: ['rectus abdominis', 'deep core'],
    secondaryMuscles: ['hip flexors'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 20 },
    intendedFeeling:
      'You should feel your braced hollow position holding firm as you rock, with no loss of the lower back pressed flat against the floor.',
    cues: [
      'Set a strong hollow-body position before you start rocking',
      'Rock from your shoulders to your heels using small, controlled momentum',
      'Keep your lower back pressed down throughout the rock',
      'Stop the set the moment the hollow position breaks down',
    ],
    commonMistakes: [
      'Letting the lower back arch off the floor during the rock',
      'Rocking with too much momentum to hide a weak hollow position',
      'Extending the arms and legs further than the brace can support',
    ],
    substitutions: ['hollow-body-hold'],
  },
  {
    id: 'hollow-body-hold',
    name: 'Hollow-Body Hold',
    category: 'calisthenics',
    primaryMuscles: ['rectus abdominis', 'deep core'],
    secondaryMuscles: ['hip flexors'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 20, maxSeconds: 40 },
    intendedFeeling:
      'You should feel your entire abdominal wall braced hard, with your lower back pressed flat and no strain in your neck or hip flexors.',
    cues: [
      'Press your lower back into the floor',
      'Keep your ribs pulled down, not flared',
      'Extend arms and legs only as far as you can hold the brace',
      'Breathe while keeping the brace, do not hold your breath',
    ],
    commonMistakes: [
      'Letting the lower back arch off the floor',
      'Pulling on the neck instead of bracing the abs',
      'Extending the legs too low too soon and losing the hollow position',
    ],
    substitutions: ['hollow-body-rock'],
  },
  {
    id: 'ab-wheel',
    name: 'Ab Wheel',
    category: 'hypertrophy',
    primaryMuscles: ['rectus abdominis', 'deep core'],
    secondaryMuscles: ['shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['other'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your entire ab wall bracing hard to control the rollout and pull you back, with no strain in your lower back.',
    cues: [
      'Brace your abs hard before you start rolling',
      'Roll out only as far as you can keep your lower back from sagging',
      'Keep your hips from arching down as you extend',
      'Pull back in using your abs, not just momentum',
    ],
    commonMistakes: [
      'Letting the lower back sag or arch during the rollout',
      'Rolling out further than current strength allows',
      'Using the hip flexors to yank back in instead of the abs',
    ],
    substitutions: ['ab-rollout-from-feet'],
  },
  {
    id: 'ab-rollout-from-feet',
    name: 'Ab Rollout From Feet',
    category: 'calisthenics',
    primaryMuscles: ['rectus abdominis', 'deep core'],
    secondaryMuscles: ['shoulders', 'lats'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['other'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 10 },
    intendedFeeling:
      'You should feel a significantly harder core brace than a kneeling rollout, since your legs no longer share the load.',
    cues: [
      'Stand with the wheel set in front of your feet',
      'Brace hard and roll out only as far as your lower back stays flat',
      'Keep a straight line from shoulders to ankles at full extension',
      'Pull back in leading with the abs, not a hip-flexor jerk',
    ],
    commonMistakes: [
      'Attempting this before the kneeling version is fully controlled',
      'Letting the lower back sag at full extension',
      'Using the hip flexors to yank back up instead of a controlled pull',
    ],
    substitutions: ['ab-wheel'],
  },

  // --- Hip-flexor-driven hanging and raise work ---
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    category: 'hypertrophy',
    primaryMuscles: ['rectus abdominis', 'hip flexors'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['pull-up-bar'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your lower abs curling your hips up with your legs straight, not just your hip flexors swinging them forward.',
    cues: [
      'Hang with a slight hollow position before you start',
      'Keep your legs straight and curl your hips up and back',
      'Raise your legs as high as you can control without swinging',
      'Lower with control instead of letting the legs drop',
    ],
    commonMistakes: [
      'Swinging the body to generate momentum',
      'Bending the knees to make the raise easier without meaning to',
      'Only using the hip flexors without curling the pelvis',
    ],
    substitutions: ['hanging-knee-raise', 'toes-to-bar'],
  },
  {
    id: 'hanging-knee-raise',
    name: 'Hanging Knee Raise',
    category: 'hypertrophy',
    primaryMuscles: ['rectus abdominis', 'hip flexors'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['pull-up-bar'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your lower abs curling your hips up, not just your hip flexors swinging your legs.',
    cues: [
      'Hang with a slight hollow position before you start',
      'Curl your hips up and back rather than just swinging the legs forward',
      'Raise your knees as high as you can control',
      'Lower with control instead of letting the legs drop and swing',
    ],
    commonMistakes: [
      'Using momentum and swinging instead of curling the hips',
      'Only lifting the legs from the hip flexors without curling the pelvis',
      'Kipping the whole body to move more reps',
    ],
    substitutions: ['hanging-leg-raise', 'captains-chair-knee-raise'],
  },
  {
    id: 'toes-to-bar',
    name: 'Toes to Bar',
    category: 'calisthenics',
    primaryMuscles: ['rectus abdominis', 'hip flexors'],
    secondaryMuscles: ['lats', 'grip'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['pull-up-bar'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 10 },
    intendedFeeling:
      'You should feel your abs and hip flexors driving your straight legs all the way to the bar, with your lats engaged to keep your body from swinging wildly.',
    cues: [
      'Start from a controlled hang with your lats engaged',
      'Drive your straight legs up toward the bar, leading with your toes',
      'Curl your hips under as your legs approach the top',
      'Lower under control rather than letting the legs free-fall',
    ],
    commonMistakes: [
      'Kipping excessively to fling the legs up',
      'Bending the knees to make the reach easier',
      'Losing the hang position between reps',
    ],
    substitutions: ['hanging-leg-raise'],
  },
  {
    id: 'captains-chair-knee-raise',
    name: "Captain's Chair Knee Raise",
    category: 'hypertrophy',
    primaryMuscles: ['rectus abdominis', 'hip flexors'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your lower abs curling your knees up toward your chest, with the arm pads taking the grip demand out of the equation.',
    cues: [
      'Rest your forearms on the pads with your back against the support',
      'Curl your knees up toward your chest using your abs',
      'Avoid swinging your torso to help lift the knees',
      'Lower under control back to a dead hang position',
    ],
    commonMistakes: [
      'Swinging the torso backward to generate momentum',
      'Only lifting from the hip flexors without curling the pelvis',
      'Rushing reps instead of pausing at the top',
    ],
    substitutions: ['hanging-knee-raise'],
  },

  // --- Anti-extension and isometric bracing ---
  {
    id: 'weighted-plank',
    name: 'Weighted Plank',
    category: 'hypertrophy',
    primaryMuscles: ['deep core', 'rectus abdominis'],
    secondaryMuscles: ['shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['other'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 30, maxSeconds: 45 },
    intendedFeeling:
      'You should feel your entire trunk bracing hard against the added load to keep your hips from sagging or piking.',
    cues: [
      'Set a plate across your upper back before getting into position',
      'Keep a straight line from shoulders to heels',
      'Brace your abs and glutes to prevent the hips from sagging',
      'Breathe steadily through the hold rather than bracing your breath',
    ],
    commonMistakes: [
      'Letting the hips sag toward the floor as fatigue sets in',
      'Piking the hips up to relieve the load',
      'Loading more weight than the position can hold with good form',
    ],
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    category: 'calisthenics',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['deep core'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 20, maxSeconds: 40, perSide: true },
    intendedFeeling:
      'You should feel the side of your torso bracing to keep your hips lifted and level, with no sagging toward the floor or rotating forward.',
    cues: [
      'Stack your feet, hips, and shoulders in one straight line',
      'Lift your hips until your body forms a straight diagonal line',
      'Keep your hips from sagging or rotating forward',
      'Breathe steadily through the hold',
    ],
    commonMistakes: [
      'Letting the hips sag toward the floor',
      'Rotating the hips forward instead of staying stacked',
      'Holding the breath instead of breathing through it',
    ],
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['deep core'],
    secondaryMuscles: ['hip flexors'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12, perSide: true },
    intendedFeeling:
      'You should feel your deep core bracing to keep your lower back flat against the floor as your opposite arm and leg extend.',
    cues: [
      'Press your lower back flat into the floor before moving',
      'Extend one arm and the opposite leg slowly',
      'Stop the extension the moment your lower back wants to arch',
      'Return under control and switch sides',
    ],
    commonMistakes: [
      'Letting the lower back arch off the floor as the limbs extend',
      'Moving too fast to control the brace',
      'Extending further than the core can stabilize',
    ],
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['deep core'],
    secondaryMuscles: ['lower back', 'glutes'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12, perSide: true },
    intendedFeeling:
      'You should feel your core bracing to keep your hips and spine still and level as your opposite arm and leg extend.',
    cues: [
      'Set up on hands and knees with a neutral spine',
      'Extend one arm and the opposite leg without letting the hips rotate',
      'Keep your core braced so your lower back stays still',
      'Return under control and switch sides',
    ],
    commonMistakes: [
      'Letting the hips rotate or tilt as the limbs extend',
      'Arching the lower back to gain more reach',
      'Moving too fast to keep the trunk stable',
    ],
  },

  // --- Anti-rotation and rotational ---
  {
    id: 'pallof-press',
    name: 'Pallof Press',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['deep core'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 12, perSide: true },
    intendedFeeling:
      'You should feel your core resisting the cable trying to rotate your torso, with your hips and shoulders staying square the entire press.',
    cues: [
      'Stand side-on to the cable with your hands at your chest',
      'Press straight out in front of you without letting your torso rotate',
      'Hold the press briefly, resisting the pull back',
      'Return under control and reset before the next rep',
    ],
    commonMistakes: [
      'Letting the torso rotate toward the cable',
      'Using a load heavy enough to break the anti-rotation brace',
      'Rushing the press instead of controlling the hold',
    ],
    substitutions: ['cable-woodchop'],
  },
  {
    id: 'cable-woodchop',
    name: 'Cable Woodchop',
    category: 'hypertrophy',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['deep core'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15, perSide: true },
    intendedFeeling:
      'You should feel your obliques driving the rotation from high to low or low to high, with the power coming from your trunk, not your arms.',
    cues: [
      'Set the cable at the height that matches the chop direction',
      'Rotate through your trunk, keeping your arms relatively fixed relative to your chest',
      'Pivot your back foot to let the hips rotate with the torso',
      'Control the return back to the start',
    ],
    commonMistakes: [
      'Pulling with the arms instead of rotating through the trunk',
      'Using so much weight that the movement becomes a yank',
      'Keeping the feet planted and losing hip rotation',
    ],
    substitutions: ['landmine-rotation', 'pallof-press'],
  },
  {
    id: 'landmine-rotation',
    name: 'Landmine Rotation',
    category: 'hypertrophy',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['deep core', 'shoulders'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your obliques and deep core controlling the bar as it sweeps side to side, with your arms staying relatively straight and passive.',
    cues: [
      'Hold the bar at the end with both hands, arms extended',
      'Rotate through your trunk to sweep the bar from side to side',
      'Let your hips and feet pivot naturally with the rotation',
      'Control the sweep rather than letting the bar swing on momentum',
    ],
    commonMistakes: [
      'Using the arms and shoulders to muscle the bar over instead of rotating the trunk',
      'Letting momentum take over instead of a controlled sweep',
      'Keeping the feet locked flat and restricting hip rotation',
    ],
    substitutions: ['cable-woodchop'],
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    category: 'hypertrophy',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['deep core'],
    progressionType: 'double-progression',
    muscleGroup: 'core',
    equipment: ['medicine-ball'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 16, maxReps: 20 },
    intendedFeeling:
      'You should feel your obliques rotating your torso side to side while your lower body stays braced and still.',
    cues: [
      'Sit with your torso leaned back and knees bent, feet lifted or planted',
      'Rotate your torso to tap the weight down on each side',
      'Keep the rotation coming from the trunk, not just the arms',
      'Keep your chest up rather than rounding forward',
    ],
    commonMistakes: [
      'Swinging the arms without rotating the torso',
      'Rounding the back to make the twist easier',
      'Moving fast enough that control breaks down',
    ],
  },

  // --- Loaded carries and sled work (full-body, core bracing under load) ---
  {
    id: 'suitcase-carry',
    name: 'Suitcase Carry',
    category: 'hypertrophy',
    primaryMuscles: ['obliques', 'grip'],
    secondaryMuscles: ['deep core', 'forearms'],
    progressionType: 'double-progression',
    muscleGroup: 'full-body',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'distance', sets: 3, meters: 30 },
    intendedFeeling:
      'You should feel the loaded side of your obliques and core fighting to keep your torso upright and level, resisting the pull toward the weight.',
    cues: [
      'Pick up the weight in one hand and stand tall before walking',
      'Keep your torso upright, resisting the lean toward the loaded side',
      'Keep your shoulders level and square the entire walk',
      'Switch hands and repeat the distance for the other side',
    ],
    commonMistakes: [
      'Leaning the torso toward the loaded side to compensate',
      'Letting the shoulder on the loaded side drop',
      'Walking too fast to keep the trunk controlled',
    ],
    substitutions: ['farmer-carry'],
  },
  {
    id: 'farmer-carry',
    name: 'Farmer Carry',
    category: 'hypertrophy',
    primaryMuscles: ['forearms', 'grip'],
    secondaryMuscles: ['traps', 'deep core'],
    progressionType: 'double-progression',
    muscleGroup: 'full-body',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'distance', sets: 3, meters: 30 },
    intendedFeeling:
      'You should feel your grip and traps working to hold the weight while your core braces to keep your torso tall and stable as you walk.',
    cues: [
      'Pick up a weight in each hand and stand fully tall before moving',
      'Keep your shoulders back and down, not shrugged up',
      'Take controlled steps, keeping your torso upright',
      'Set the weights down under control at the end of the distance',
    ],
    commonMistakes: [
      'Letting the shoulders round forward under the load',
      'Rushing the walk and losing control of the weights',
      'Leaning the torso side to side to compensate for grip fatigue',
    ],
    substitutions: ['suitcase-carry', 'overhead-carry'],
  },
  {
    id: 'overhead-carry',
    name: 'Overhead Carry',
    category: 'hypertrophy',
    primaryMuscles: ['shoulders', 'deep core'],
    secondaryMuscles: ['triceps'],
    progressionType: 'double-progression',
    muscleGroup: 'full-body',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'distance', sets: 3, meters: 30 },
    intendedFeeling:
      'You should feel your shoulders locked in place overhead and your core bracing hard to keep your ribs from flaring as you walk.',
    cues: [
      'Press the weights fully overhead before you start walking',
      'Keep your ribs down and core braced throughout',
      'Keep the weights stacked directly over your shoulders, not drifting forward',
      'Lower the weights under control at the end of the distance',
    ],
    commonMistakes: [
      'Letting the ribs flare and the lower back arch',
      'Letting the arms drift forward of the shoulders',
      'Walking before the overhead position is fully locked out',
    ],
    substitutions: ['farmer-carry'],
  },
  {
    id: 'sled-push',
    name: 'Sled Push',
    category: 'strength',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves', 'deep core'],
    progressionType: 'double-progression',
    muscleGroup: 'full-body',
    equipment: ['sled'],
    defaultPrescription: { type: 'distance', sets: 3, meters: 20 },
    intendedFeeling:
      'You should feel your legs driving hard into the ground the whole distance, with your core braced to keep your torso rigid against the load.',
    cues: [
      'Set a forward lean with your arms extended on the handles',
      'Drive through the balls of your feet with long, powerful steps',
      'Keep your torso rigid rather than letting your hips sag',
      'Keep your steps under control rather than choppy and rushed',
    ],
    commonMistakes: [
      'Standing too upright and losing leg drive',
      'Letting the hips sag or the lower back round',
      'Taking short, frantic steps instead of powerful ones',
    ],
    substitutions: ['sled-drag'],
  },
  {
    id: 'sled-drag',
    name: 'Sled Drag',
    category: 'hypertrophy',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['quads', 'deep core'],
    progressionType: 'double-progression',
    muscleGroup: 'full-body',
    equipment: ['sled'],
    defaultPrescription: { type: 'distance', sets: 3, meters: 20 },
    intendedFeeling:
      'You should feel your hamstrings and glutes driving each step backward or forward against the resistance, with your core braced to keep your torso stable.',
    cues: [
      'Attach the strap or harness securely before loading the sled',
      'Take controlled, deliberate steps against the resistance',
      'Keep your torso braced and stable throughout',
      'Keep tension on the strap the whole distance, avoid jerky steps',
    ],
    commonMistakes: [
      'Taking steps too fast to control against the resistance',
      'Letting the torso twist or lean excessively',
      'Losing tension on the strap between steps',
    ],
    substitutions: ['sled-push'],
  },
];
