import type { CatalogExercise } from '../program-types';

/**
 * Mobility and rehabilitation/prehab exercise library (R10). Preserves
 * Wrist Preparation, Dynamic Warm-Up, and Mobility Flow from the pre-R10
 * catalog verbatim (name/category/muscles/progression untouched, no
 * guidance existed before so it is written fresh here), adding only
 * muscleGroup, equipment, and defaultPrescription. Every other entry is
 * new library content: joint prep drills, static stretches, and corrective
 * work, plus the qualitative Mobility Flow preset (the former Lower and
 * Upper Body Mobility folded into it on 2026-09-05). No walking-based
 * warm-ups live here; machine cardio and dead hangs live in their own
 * files.
 */
export const MOBILITY_PREHAB_EXERCISES: CatalogExercise[] = [
  // --- Preserved ---
  {
    id: 'wrist-preparation',
    name: 'Wrist Preparation',
    category: 'mobility',
    primaryMuscles: ['wrists', 'forearms'],
    secondaryMuscles: [],
    progressionType: 'none',
    muscleGroup: 'forearms',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'duration', sets: 1, minSeconds: 120, maxSeconds: 180 },
    intendedFeeling:
      'You should feel your wrists warming up and loosening through flexion, extension, and light loading, with no sharp or pinching pain anywhere in the joint.',
    cues: [
      'Move through wrist circles in both directions',
      'Add gentle loaded rocking on flat palms once the joint feels warm',
      'Keep movements slow and controlled rather than fast and loose',
      'Stop and reduce range if anything feels sharp rather than a mild stretch',
    ],
    commonMistakes: [
      'Skipping straight to loaded pressing without warming the joint first',
      'Forcing a painful range instead of backing off',
      'Rushing through so fast the wrists never actually warm up',
    ],
  },
  {
    id: 'dynamic-warm-up',
    name: 'Dynamic Warm-Up',
    category: 'mobility',
    primaryMuscles: ['full body'],
    secondaryMuscles: [],
    progressionType: 'none',
    muscleGroup: 'full-body',
    equipment: ['bodyweight'],
    defaultPrescription: {
      type: 'qualitative',
      description: 'Progress through general dynamic movement to raise body temperature and prepare joints for training.',
      approxMinMinutes: 6,
      approxMaxMinutes: 10,
    },
    intendedFeeling:
      'You should feel your whole body gradually warming up, with joints moving more freely by the end than when you started.',
    cues: [
      'Start with easy, low intensity movement and build gradually',
      'Move every major joint through a comfortable range',
      'Keep the pace controlled rather than rushing through it',
      'Finish only once you feel genuinely warm and loose',
    ],
    commonMistakes: [
      'Rushing through so fast that nothing actually warms up',
      'Skipping joints that will be loaded heavily in the session',
      'Treating it as a stretch to hold rather than movement to flow through',
    ],
  },
  {
    id: 'mobility-flow',
    name: 'Mobility Flow',
    category: 'mobility',
    primaryMuscles: ['hips', 'ankles', 'shoulders', 'thoracic spine', 'wrists'],
    secondaryMuscles: [],
    progressionType: 'none',
    muscleGroup: 'full-body',
    equipment: ['bodyweight'],
    defaultPrescription: {
      type: 'qualitative',
      description: 'Move through controlled, comfortable ranges across the hips, ankles, shoulders, spine, and wrists.',
      approxMinMinutes: 12,
      approxMaxMinutes: 15,
    },
    intendedFeeling:
      'You should feel each joint moving through a comfortable, controlled range, leaving you feeling looser and more mobile than when you started, never strained.',
    cues: [
      'Move through each region in turn rather than rushing between them',
      'Stay inside a comfortable range, do not force end range',
      'Breathe steadily throughout rather than holding your breath',
      'Slow down on any area that feels particularly tight that day',
    ],
    commonMistakes: [
      'Rushing through so fast that nothing meaningfully improves',
      'Forcing an aggressive stretch into an irritated area',
      'Skipping regions that feel fine that day instead of covering everything briefly',
    ],
  },

  // --- Hip and adductor mobility ---
  {
    id: '90-90-hip-switch',
    name: '90/90 Hip Switch',
    category: 'mobility',
    primaryMuscles: ['hips'],
    secondaryMuscles: ['adductors', 'glutes'],
    progressionType: 'none',
    muscleGroup: 'hips',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 8, maxReps: 10 },
    intendedFeeling:
      'You should feel both hips rotating through internal and external rotation as you switch sides, without pinching pain in either hip.',
    cues: [
      'Keep both sit bones on the floor as you rotate',
      'Move slowly enough to control the transition between sides',
      'Keep your torso relatively upright rather than leaning back for momentum',
      'Stop short of any pinching sensation in the hip joint',
    ],
    commonMistakes: [
      'Using the arms to yank the body around instead of rotating through the hips',
      'Rushing the switch and losing control of the position',
      'Forcing a deeper position than the hip currently allows',
    ],
  },
  {
    id: 'couch-stretch',
    name: 'Couch Stretch',
    category: 'mobility',
    primaryMuscles: ['hips'],
    secondaryMuscles: ['quadriceps'],
    progressionType: 'none',
    muscleGroup: 'hips',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'hold', sets: 2, minSeconds: 30, maxSeconds: 60, perSide: true },
    intendedFeeling:
      'You should feel a stretch through the front of your hip and quad on the back leg, with your torso staying upright rather than leaning forward.',
    cues: [
      'Keep your back shin against a wall or bench behind you',
      'Squeeze the glute on the stretched side to deepen the hip stretch',
      'Keep your torso tall rather than leaning forward to escape the stretch',
      'Ease into the position gradually rather than dropping in fast',
    ],
    commonMistakes: [
      'Leaning the torso forward, which reduces the actual hip stretch',
      'Arching the lower back to compensate for limited hip range',
      'Forcing a deeper position before the hip is ready for it',
    ],
  },
  {
    id: 'pigeon-stretch',
    name: 'Pigeon Stretch',
    category: 'mobility',
    primaryMuscles: ['hips'],
    secondaryMuscles: ['glutes'],
    progressionType: 'none',
    muscleGroup: 'hips',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'hold', sets: 2, minSeconds: 30, maxSeconds: 60, perSide: true },
    intendedFeeling:
      'You should feel a deep stretch through the outer hip and glute of your front leg, with your hips staying relatively square to the floor.',
    cues: [
      'Keep your front shin angled comfortably rather than forcing it parallel',
      'Keep your hips square rather than letting one side lift',
      'Sink into the stretch gradually as the hip allows',
      'Breathe steadily rather than tensing against the stretch',
    ],
    commonMistakes: [
      'Letting the back hip rotate open to fake more range',
      'Forcing the front shin into a position that causes knee pain',
      'Holding the breath instead of relaxing into the position',
    ],
  },
  {
    id: 'hip-flexor-stretch',
    name: 'Hip Flexor Stretch',
    category: 'mobility',
    primaryMuscles: ['hips'],
    secondaryMuscles: ['hip flexors'],
    progressionType: 'none',
    muscleGroup: 'hips',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'hold', sets: 2, minSeconds: 20, maxSeconds: 40, perSide: true },
    intendedFeeling:
      'You should feel a stretch through the front of the hip on your back leg, without your lower back arching to reach the position.',
    cues: [
      'Tuck your pelvis slightly under to isolate the hip flexor stretch',
      'Squeeze the glute on the back leg to deepen the stretch',
      'Keep your torso upright rather than leaning forward',
      'Ease into the stretch rather than forcing depth',
    ],
    commonMistakes: [
      'Arching the lower back to fake a deeper stretch',
      'Leaning the torso forward instead of keeping it tall',
      'Rushing in and out of the position instead of holding steady',
    ],
  },
  {
    id: 'adductor-rock-back',
    name: 'Adductor Rock Back',
    category: 'mobility',
    primaryMuscles: ['hips'],
    secondaryMuscles: ['adductors'],
    progressionType: 'none',
    muscleGroup: 'hips',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 10, maxReps: 15, perSide: true },
    intendedFeeling:
      'You should feel a controlled stretch along your inner thigh as you rock back, staying inside a comfortable, pain-free range.',
    cues: [
      'Keep the stretched leg straight and turned slightly outward',
      'Rock your hips straight back rather than to one side',
      'Stay inside a controlled, comfortable range',
      'Build range gradually across sessions rather than forcing it in one set',
    ],
    commonMistakes: [
      'Forcing a painful or provocative range on an irritated groin',
      'Rocking to the side instead of straight back',
      'Bouncing at end range instead of controlled repetitions',
    ],
  },
  {
    id: 'deep-squat-hold',
    name: 'Deep Squat Hold',
    category: 'mobility',
    primaryMuscles: ['hips'],
    secondaryMuscles: ['ankles', 'lower back'],
    progressionType: 'none',
    muscleGroup: 'hips',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'hold', sets: 2, minSeconds: 30, maxSeconds: 60 },
    intendedFeeling:
      'You should feel your hips and ankles opening into a deep, relaxed squat, with your heels staying down and your spine reasonably tall.',
    cues: [
      'Keep your heels flat on the floor',
      'Use your elbows to gently press your knees outward if needed',
      'Keep your chest relatively tall rather than collapsing forward',
      'Shift your weight gently side to side to explore the position',
    ],
    commonMistakes: [
      'Letting the heels lift off the floor',
      'Rounding the lower back heavily to sink deeper',
      'Forcing the position instead of settling into it gradually',
    ],
  },

  // --- Ankle and calf mobility ---
  {
    id: 'ankle-dorsiflexion-rock',
    name: 'Ankle Dorsiflexion Rock',
    category: 'mobility',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['tibialis anterior'],
    progressionType: 'none',
    muscleGroup: 'calves',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 10, maxReps: 15, perSide: true },
    intendedFeeling:
      'You should feel a stretch through the back of your ankle and calf as your knee drives forward over your toes, with your heel staying flat.',
    cues: [
      'Keep your heel flat on the floor throughout',
      'Drive your knee forward over your toes under control',
      'Keep your foot pointing straight ahead',
      'Rock at a controlled pace rather than bouncing',
    ],
    commonMistakes: [
      'Letting the heel lift as the knee drives forward',
      'Letting the knee cave inward instead of tracking over the toes',
      'Bouncing aggressively instead of a controlled rock',
    ],
  },
  {
    id: 'calf-stretch-wall',
    name: 'Calf Stretch (Wall)',
    category: 'mobility',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['soleus'],
    progressionType: 'none',
    muscleGroup: 'calves',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'hold', sets: 2, minSeconds: 20, maxSeconds: 30, perSide: true },
    intendedFeeling:
      'You should feel a steady stretch through your calf on the straight back leg, with your heel staying planted the entire hold.',
    cues: [
      'Keep your back leg straight and heel flat on the floor',
      'Point your back foot straight ahead, not turned out',
      'Lean forward from the ankle rather than rounding your back',
      'Bend the back knee slightly to shift the stretch lower toward the soleus',
    ],
    commonMistakes: [
      'Letting the back heel lift off the floor',
      'Turning the back foot outward, reducing the stretch',
      'Bouncing in and out of the stretch instead of holding steady',
    ],
  },

  // --- Spine and shoulder mobility ---
  {
    id: 'thoracic-extension-over-foam-roller',
    name: 'Thoracic Extension Over Foam Roller',
    category: 'mobility',
    primaryMuscles: ['back'],
    secondaryMuscles: ['shoulders'],
    progressionType: 'none',
    muscleGroup: 'back',
    equipment: ['other'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your upper back extending over the roller while your lower back and hips stay relaxed and neutral.',
    cues: [
      'Support your head with your hands rather than pulling on your neck',
      'Keep your hips down and lower back relaxed, not arching from there',
      'Extend from the point where the roller sits under your upper back',
      'Move slowly and breathe out as you extend',
    ],
    commonMistakes: [
      'Extending mostly through the lower back instead of the upper back',
      'Pulling on the neck to force extension',
      'Moving too fast to actually feel the segment opening up',
    ],
  },
  {
    id: 'open-book-rotation',
    name: 'Open Book Rotation',
    category: 'mobility',
    primaryMuscles: ['back'],
    secondaryMuscles: ['obliques'],
    progressionType: 'none',
    muscleGroup: 'back',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 8, maxReps: 10, perSide: true },
    intendedFeeling:
      'You should feel your upper back and ribcage rotating open toward the ceiling, with your hips staying stacked and still.',
    cues: [
      'Keep your knees stacked and hips still as you rotate',
      'Lead the rotation with your chest, following with your eyes',
      'Reach your top arm as far open as feels controlled',
      'Return slowly rather than letting the arm drop',
    ],
    commonMistakes: [
      'Letting the hips rotate along with the chest, hiding the actual thoracic rotation',
      'Rushing the movement instead of controlling both directions',
      'Forcing more rotation than currently available',
    ],
  },
  {
    id: 'cat-cow',
    name: 'Cat Cow',
    category: 'mobility',
    primaryMuscles: ['back'],
    secondaryMuscles: ['core'],
    progressionType: 'none',
    muscleGroup: 'back',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your spine moving smoothly from a full round to a full arch, one segment at a time, without any pinching.',
    cues: [
      'Start from hands and knees with a neutral spine',
      'Round your back fully, tucking chin and pelvis',
      'Arch fully the other direction, lifting chest and tailbone',
      'Move slowly enough to feel each part of the spine involved',
    ],
    commonMistakes: [
      'Moving only through the lower back instead of the whole spine',
      'Rushing through the reps instead of moving with control',
      'Forcing a painful arch instead of a comfortable range',
    ],
  },
  {
    id: 'worlds-greatest-stretch',
    name: "World's Greatest Stretch",
    category: 'mobility',
    primaryMuscles: ['hips'],
    secondaryMuscles: ['shoulders', 'hamstrings', 'adductors'],
    progressionType: 'none',
    muscleGroup: 'full-body',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 5, maxReps: 8, perSide: true },
    intendedFeeling:
      'You should feel your hip flexor, hamstring, and thoracic spine all opening up in sequence as you move through the lunge, reach, and rotation.',
    cues: [
      'Step into a long lunge before adding the rotation',
      'Drop the back knee to deepen the hip flexor stretch first',
      'Rotate and reach your inside arm toward the ceiling',
      'Move through each phase deliberately rather than rushing the sequence',
    ],
    commonMistakes: [
      'Rushing straight to the rotation before settling into the lunge',
      'Letting the front knee cave inward during the stretch',
      'Skipping the hamstring reach portion of the sequence',
    ],
  },
  {
    id: 'shoulder-dislocates-band-or-stick',
    name: 'Shoulder Dislocates (Band or Stick)',
    category: 'mobility',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['chest', 'upper back'],
    progressionType: 'none',
    muscleGroup: 'shoulders',
    equipment: ['band', 'other'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel a controlled stretch moving through your shoulders as the band or stick passes from in front of your body to behind it, without pain in the front of the shoulder.',
    cues: [
      'Use a wide enough grip that the movement stays pain-free',
      'Keep your arms as straight as comfortably possible',
      'Move slowly through the full pass rather than rushing it',
      'Narrow the grip gradually over time only as range allows',
    ],
    commonMistakes: [
      'Using too narrow a grip and forcing painful shoulder range',
      'Bending the elbows to fake more range of motion',
      'Rushing the pass instead of controlling both directions',
    ],
  },
  {
    id: 'wall-slide',
    name: 'Wall Slide',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['scapular stabilizers', 'upper back'],
    progressionType: 'none',
    muscleGroup: 'shoulders',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your shoulder blades and upper back controlling the slide while your arms and lower back stay in contact with the wall.',
    cues: [
      'Keep your lower back, head, and arms in contact with the wall',
      'Slide your arms up only as far as contact can be maintained',
      'Lead the movement with your shoulder blades, not just your arms',
      'Lower under control back to the starting position',
    ],
    commonMistakes: [
      'Arching the lower back off the wall to fake more range',
      'Letting the arms lift off the wall partway through',
      'Moving too fast to actually control the shoulder blades',
    ],
  },
  {
    id: 'hanging-decompression',
    name: 'Hanging Decompression',
    category: 'mobility',
    primaryMuscles: ['back'],
    secondaryMuscles: ['shoulders', 'lats'],
    progressionType: 'none',
    muscleGroup: 'back',
    equipment: ['bodyweight', 'pull-up-bar'],
    defaultPrescription: { type: 'hold', sets: 2, minSeconds: 20, maxSeconds: 40 },
    intendedFeeling:
      'You should feel a gentle traction through your spine and shoulders as your bodyweight hangs, with your shoulders relaxed rather than shrugged up.',
    cues: [
      'Hang with a relaxed grip and let your shoulders settle',
      'Let your spine lengthen passively rather than actively pulling',
      'Keep breathing steadily throughout the hang',
      'Step down gradually rather than dropping suddenly',
    ],
    commonMistakes: [
      'Shrugging the shoulders up instead of letting them relax',
      'Holding the breath instead of breathing through the hang',
      'Hanging longer than the grip can comfortably sustain',
    ],
  },
  {
    id: 'hamstring-floss',
    name: 'Hamstring Floss',
    category: 'mobility',
    primaryMuscles: ['hips'],
    secondaryMuscles: ['lower back'],
    progressionType: 'none',
    muscleGroup: 'hips',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 8, maxReps: 12, perSide: true },
    intendedFeeling:
      'You should feel a moving stretch through the back of your leg as your neck flexes and extends in time with your leg motion, not a static, forced stretch.',
    cues: [
      'Coordinate flexing your neck forward with extending your leg',
      'Keep the working leg relatively straight without locking the knee',
      'Move rhythmically rather than holding a static end range',
      'Keep the motion gentle and pain-free throughout',
    ],
    commonMistakes: [
      'Forcing a static stretch instead of the flowing floss motion',
      'Locking the knee out hard at end range',
      'Rushing the tempo instead of a controlled, rhythmic pace',
    ],
  },
  {
    id: 'jefferson-curl',
    name: 'Jefferson Curl',
    category: 'mobility',
    primaryMuscles: ['back'],
    secondaryMuscles: ['hips'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 6, maxReps: 10 },
    intendedFeeling:
      'You should feel your spine rounding forward one segment at a time under control, with a stretch through your back and the back of your legs, never a sharp pain.',
    cues: [
      'Round forward from the neck downward, one vertebra at a time',
      'Keep the motion slow and controlled throughout',
      'Only go as deep as you can control on the way back up',
      'Reverse the curl the same slow, segmented way',
    ],
    commonMistakes: [
      'Rushing down and using momentum instead of a controlled curl',
      'Going deeper than current control allows',
      'Standing back up with a sudden jerk instead of reversing the curl',
    ],
  },

  // --- Corrective and prehab ---
  {
    id: 'banded-hip-distraction',
    name: 'Banded Hip Distraction',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['hips'],
    secondaryMuscles: [],
    progressionType: 'none',
    muscleGroup: 'hips',
    equipment: ['band'],
    defaultPrescription: { type: 'hold', sets: 2, minSeconds: 30, maxSeconds: 45, perSide: true },
    intendedFeeling:
      'You should feel gentle traction opening the hip joint as the band pulls, with the surrounding muscles able to relax into the position.',
    cues: [
      'Anchor the band low and close to the hip crease',
      'Sit back gently until you feel a mild traction sensation',
      'Move slowly through small rocks or shifts to explore the joint',
      'Stay well inside a comfortable, pain-free range',
    ],
    commonMistakes: [
      'Using a band pull strong enough to cause discomfort',
      'Rushing through instead of allowing the muscles to relax',
      'Anchoring the band at the wrong height for the joint angle intended',
    ],
  },
  {
    id: 'glute-bridge-march',
    name: 'Glute Bridge March',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['hips'],
    secondaryMuscles: ['core'],
    progressionType: 'double-progression',
    muscleGroup: 'hips',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 8, maxReps: 12, perSide: true },
    intendedFeeling:
      'You should feel your hips staying level and stable while one leg lifts and lowers, with your glutes controlling the pelvis rather than your lower back.',
    cues: [
      'Set up in a bridge with hips level before marching',
      'Lift one knee toward your chest while keeping the hips still',
      'Keep the supporting glute working to prevent the hips from dropping',
      'Lower under control and switch sides smoothly',
    ],
    commonMistakes: [
      'Letting the hips drop or rotate toward the lifted side',
      'Arching the lower back to compensate for hip instability',
      'Rushing the march instead of controlling each rep',
    ],
  },
  {
    id: 'single-leg-balance',
    name: 'Single-Leg Balance',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['full body'],
    secondaryMuscles: ['calves', 'hips'],
    progressionType: 'double-progression',
    muscleGroup: 'full-body',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'hold', sets: 2, minSeconds: 20, maxSeconds: 30, perSide: true },
    intendedFeeling:
      'You should feel small stabilizing muscles around your ankle, knee, and hip working continuously to keep you steady, not a dramatic wobble or strain.',
    cues: [
      'Find a soft focal point ahead rather than looking down',
      'Keep a very slight bend in the standing knee',
      'Let small ankle and hip adjustments happen rather than fighting them rigidly',
      'Increase difficulty gradually, such as closing the eyes, only once stable',
    ],
    commonMistakes: [
      'Locking the standing knee out completely',
      'Looking down at the floor instead of ahead',
      'Progressing to a harder variation before the current one is stable',
    ],
  },
  {
    id: 'ankle-alphabet',
    name: 'Ankle Alphabet',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['tibialis anterior'],
    progressionType: 'none',
    muscleGroup: 'calves',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'duration', sets: 1, minSeconds: 30, maxSeconds: 60, perSide: true },
    intendedFeeling:
      'You should feel your ankle moving through its full range in every direction as you trace each letter, without pain at any end range.',
    cues: [
      'Move only from the ankle, keep the rest of the leg still',
      'Trace each letter as large as comfortably possible',
      'Move slowly enough to feel the full range in every direction',
      'Stop short of any pinching or sharp sensation',
    ],
    commonMistakes: [
      'Moving from the hip or knee instead of isolating the ankle',
      'Rushing through the letters instead of tracing full range',
      'Forcing a painful range to complete the full alphabet',
    ],
  },
  {
    id: 'wrist-push-up-progression',
    name: 'Wrist Push-Up Progression',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['wrists'],
    secondaryMuscles: ['forearms'],
    progressionType: 'double-progression',
    muscleGroup: 'forearms',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your wrists loading gradually through a push up pattern, building tolerance without any sharp or pinching pain.',
    cues: [
      'Start on fists or a small incline if full range is uncomfortable',
      'Load the wrists gradually rather than jumping to full range',
      'Keep the movement slow and controlled',
      'Progress the range only once the current level feels pain-free',
    ],
    commonMistakes: [
      'Jumping straight to full flat-hand range before the wrist is ready',
      'Pushing through sharp pain instead of backing off',
      'Rushing the progression instead of building tolerance gradually',
    ],
  },
  {
    id: 'wrist-flexor-stretch',
    name: 'Wrist Flexor Stretch',
    category: 'mobility',
    primaryMuscles: ['forearms'],
    secondaryMuscles: ['wrists'],
    progressionType: 'none',
    muscleGroup: 'forearms',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'hold', sets: 2, minSeconds: 20, maxSeconds: 30, perSide: true },
    intendedFeeling:
      'You should feel a stretch along the underside of your forearm as your wrist extends and fingers point down, without pain at the wrist joint itself.',
    cues: [
      'Extend your arm and point your fingers toward the floor',
      'Gently pull the hand back with the other hand to deepen the stretch',
      'Keep your elbow straight throughout',
      'Ease in gradually rather than yanking into the stretch',
    ],
    commonMistakes: [
      'Yanking the hand back too aggressively',
      'Bending the elbow, which reduces the actual forearm stretch',
      'Forcing the stretch through joint pain rather than muscle tension',
    ],
  },
  {
    id: 'prone-y-raise',
    name: 'Prone Y Raise',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['back'],
    secondaryMuscles: ['shoulders', 'rotator cuff'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your lower traps and upper back working as your arms lift overhead in a Y shape, not your lower back arching to help.',
    cues: [
      'Lie face down with arms extended overhead in a Y position',
      'Lift your arms using your upper back, not your lower back',
      'Keep your ribs down and avoid arching to gain height',
      'Lower under control between reps',
    ],
    commonMistakes: [
      'Arching the lower back to lift the arms higher',
      'Using momentum instead of a controlled lift',
      'Shrugging the shoulders instead of engaging the upper back',
    ],
  },
  {
    id: 'prone-t-raise',
    name: 'Prone T Raise',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['back'],
    secondaryMuscles: ['rear deltoid'],
    progressionType: 'double-progression',
    muscleGroup: 'back',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your rear shoulders and upper back squeezing together as your arms lift out to the sides, not your lower back arching for height.',
    cues: [
      'Lie face down with arms extended out to the sides in a T position',
      'Lift your arms by squeezing your shoulder blades together',
      'Keep your ribs down and avoid arching your lower back',
      'Lower under control between reps',
    ],
    commonMistakes: [
      'Arching the lower back to gain more height',
      'Using momentum to swing the arms up',
      'Shrugging instead of squeezing the shoulder blades',
    ],
  },
  {
    id: 'foam-rolling',
    name: 'Foam Rolling',
    category: 'mobility',
    primaryMuscles: ['full body'],
    secondaryMuscles: [],
    progressionType: 'none',
    muscleGroup: 'full-body',
    equipment: ['other'],
    defaultPrescription: {
      type: 'qualitative',
      description: 'Roll major muscle groups at a slow, controlled pace to reduce tightness before or after training.',
      approxMinMinutes: 5,
      approxMaxMinutes: 10,
    },
    intendedFeeling:
      'You should feel a moderate, tolerable pressure that eases as you hold or roll over a spot, never a sharp or bruising pain.',
    cues: [
      'Roll slowly rather than fast back and forth',
      'Pause briefly on tender spots rather than rolling straight through',
      'Keep your breathing steady rather than tensing against the pressure',
      'Avoid rolling directly over joints or bone',
    ],
    commonMistakes: [
      'Rolling too fast to actually affect the tissue',
      'Applying so much pressure that it causes bruising or sharp pain',
      'Rolling directly over a joint instead of the surrounding muscle',
    ],
  },
];
