import type { CatalogExercise } from '../program-types';

// Hip-hinge, hamstring, glute, and hip-stabilizer work: the posterior chain
// and the hip stabilizers that support sprinting and cutting. Three
// muscleGroups live in this one file: hamstrings, glutes, hips.

export const POSTERIOR_CHAIN_EXERCISES: CatalogExercise[] = [
  // --- Hamstrings: hinge pattern ---
  {
    id: 'conventional-deadlift',
    name: 'Conventional Deadlift',
    category: 'strength',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower back', 'traps'],
    progressionType: 'double-progression',
    muscleGroup: 'hamstrings',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 5, maxReps: 8 },
    intendedFeeling:
      'You should feel your hamstrings and glutes driving the pull from the floor, with your torso staying rigid and your lower back never rounding under load.',
    cues: [
      'Set your shins close to the bar with your hips higher than your knees',
      'Take the slack out of the bar before you pull',
      'Push the floor away with your legs to start the lift',
      'Keep the bar close to your body all the way up',
    ],
    commonMistakes: [
      'Rounding the lower back to reach the bar',
      'Letting the hips shoot up first, turning it into a stiff-leg pull',
      'Jerking the bar off the floor instead of building tension first',
    ],
    substitutions: ['trap-bar-deadlift', 'sumo-deadlift'],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'hypertrophy',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower back'],
    progressionType: 'double-progression',
    muscleGroup: 'hamstrings',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 10 },
    intendedFeeling:
      'You should feel a strong stretch through your hamstrings as you hinge, with your glutes finishing the rep.',
    cues: [
      'Push your hips back first, knees stay soft, not bent further',
      'Keep the bar or dumbbells close to your legs',
      'Lower only until you feel a full hamstring stretch',
      'Drive your hips forward to stand, squeezing the glutes',
    ],
    commonMistakes: [
      'Rounding the lower back to reach further down',
      'Bending the knees like a squat instead of hinging',
      'Standing up by leaning back with the shoulders instead of the hips',
    ],
    substitutions: ['dumbbell-romanian-deadlift', 'single-leg-romanian-deadlift'],
  },
  {
    id: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    category: 'hypertrophy',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower back'],
    progressionType: 'double-progression',
    muscleGroup: 'hamstrings',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel the same hamstring stretch as a barbell Romanian deadlift, with the dumbbells letting you find a comfortable hand path along your legs.',
    cues: [
      'Push your hips back while keeping a soft bend in the knees',
      'Keep the dumbbells brushing against your legs on the way down',
      'Lower only until your hamstrings reach a full stretch',
      'Drive your hips forward to finish, squeezing the glutes',
    ],
    commonMistakes: [
      'Letting the dumbbells drift forward away from the legs',
      'Rounding the lower back to chase more range',
      'Turning it into a squat by bending the knees more instead of hinging',
    ],
    substitutions: ['romanian-deadlift', 'single-leg-romanian-deadlift'],
  },
  {
    id: 'single-leg-romanian-deadlift',
    name: 'Single-Leg Romanian Deadlift',
    category: 'hypertrophy',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower back'],
    progressionType: 'double-progression',
    muscleGroup: 'hamstrings',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12, perSide: true },
    intendedFeeling:
      'You should feel your standing leg hamstring stretching and controlling the hinge, with your hips staying square instead of rotating open.',
    cues: [
      'Keep a soft bend in the standing knee throughout',
      'Hinge at the hip, letting the back leg rise as a counterbalance',
      'Keep your hips square to the floor, do not let them open up',
      'Drive back to standing through the working leg',
    ],
    commonMistakes: [
      'Letting the hips rotate open instead of staying square',
      'Rushing the balance instead of controlling the hinge',
      'Turning it into a stiff kickback instead of a controlled hinge',
    ],
    substitutions: ['romanian-deadlift', 'dumbbell-romanian-deadlift'],
  },
  {
    id: 'stiff-leg-deadlift',
    name: 'Stiff-Leg Deadlift',
    category: 'hypertrophy',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'lower back'],
    progressionType: 'double-progression',
    muscleGroup: 'hamstrings',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel a deep hamstring stretch from a nearly straight-leg hinge, more intense than a Romanian deadlift, without your lower back rounding to reach it.',
    cues: [
      'Keep your knees just barely soft, not bending through the rep',
      'Hinge at the hips and lower the bar close to your legs',
      'Stop the descent the moment your lower back wants to round',
      'Drive your hips forward to return to standing',
    ],
    commonMistakes: [
      'Bending the knees to fake more range',
      'Rounding the lower back to reach the floor',
      'Using momentum to bounce out of the bottom',
    ],
    substitutions: ['romanian-deadlift'],
  },
  {
    id: 'good-morning',
    name: 'Good Morning',
    category: 'hypertrophy',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['lower back', 'glutes'],
    progressionType: 'double-progression',
    muscleGroup: 'hamstrings',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your hamstrings and lower back working together to control the hinge, with the bar staying light enough that form never breaks down.',
    cues: [
      'Set the bar across your upper back like a squat',
      'Push your hips back with a soft knee bend as your torso lowers',
      'Keep your spine neutral throughout, not rounding or overarching',
      'Drive your hips forward to return upright',
    ],
    commonMistakes: [
      'Rounding the lower back under load',
      'Bending the knees too much and turning it into a squat',
      'Using more weight than the lower back can stabilize',
    ],
    substitutions: ['stiff-leg-deadlift'],
  },
  {
    id: 'nordic-hamstring-curl',
    name: 'Nordic Hamstring Curl',
    category: 'calisthenics',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'hamstrings',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 4, maxReps: 8 },
    intendedFeeling:
      'You should feel an intense eccentric load through your hamstrings as you resist falling forward, with your hips staying extended throughout.',
    cues: [
      'Anchor your ankles securely before starting',
      'Keep your hips extended in a straight line from knee to shoulder',
      'Lower yourself forward as slowly as you can control',
      'Catch yourself with your hands only once control is lost, then reset',
    ],
    commonMistakes: [
      'Letting the hips bend and fold instead of staying extended',
      'Dropping fast instead of resisting the fall',
      'Pushing back up with the arms rather than the hamstrings',
    ],
    substitutions: ['glute-ham-raise'],
  },
  {
    id: 'glute-ham-raise',
    name: 'Glute-Ham Raise',
    category: 'calisthenics',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes'],
    progressionType: 'double-progression',
    muscleGroup: 'hamstrings',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 10 },
    intendedFeeling:
      'You should feel your hamstrings working through both the lowering and raising portions of the rep, with your glutes assisting near the top.',
    cues: [
      'Set your knees at the pad with your ankles secured',
      'Lower your torso under control, resisting the fall with your hamstrings',
      'Curl back up leading with the hamstrings before the glutes finish it',
      'Keep a straight line from knee to shoulder throughout',
    ],
    commonMistakes: [
      'Letting the hips bend early instead of staying extended',
      'Dropping through the bottom instead of controlling the descent',
      'Using momentum to swing back up',
    ],
    substitutions: ['nordic-hamstring-curl'],
  },
  {
    id: 'seated-leg-curl',
    name: 'Seated Leg Curl',
    category: 'hypertrophy',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'hamstrings',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel the contraction concentrated in your hamstrings through the full range, from full stretch to full squeeze.',
    cues: [
      'Adjust the pad so it sits just above your heels',
      'Curl through a full range without lifting your hips off the seat',
      'Squeeze hard at the bottom of the curl',
      'Control the return back to the stretched position',
    ],
    commonMistakes: [
      'Using short, bouncy partial reps',
      'Lifting the hips or back off the pad to move more weight',
      'Letting the weight drop instead of controlling the negative',
    ],
    substitutions: ['lying-leg-curl', 'leg-curl'],
  },
  {
    id: 'lying-leg-curl',
    name: 'Lying Leg Curl',
    category: 'hypertrophy',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'hamstrings',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your hamstrings doing the work through the full curl, without your hips lifting off the bench.',
    cues: [
      'Keep your hips pressed into the bench throughout',
      'Curl your heels toward your glutes through a full range',
      'Squeeze at the top of the curl before lowering',
      'Control the eccentric rather than letting the weight drop',
    ],
    commonMistakes: [
      'Lifting the hips to help finish the rep',
      'Using momentum instead of a controlled curl',
      'Cutting the range short at either end',
    ],
    substitutions: ['seated-leg-curl', 'leg-curl'],
  },
  {
    id: 'leg-curl',
    name: 'Leg Curl',
    category: 'hypertrophy',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'hamstrings',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your hamstrings contracting through the full range, from full stretch to full squeeze.',
    cues: [
      'Set the pad position so it contacts just above your heels',
      'Curl through a full range under control',
      'Squeeze hard at the top of the curl',
      'Control the return to the stretch rather than letting it drop',
    ],
    commonMistakes: [
      'Using short, bouncy partial reps',
      'Lifting the hips to move more weight',
      'Letting the weight drop on the way back instead of controlling it',
    ],
    substitutions: ['seated-leg-curl', 'lying-leg-curl'],
  },

  // --- Glutes: hip extension pattern ---
  {
    id: 'trap-bar-deadlift',
    name: 'Trap-Bar Deadlift',
    category: 'hypertrophy',
    primaryMuscles: ['glutes', 'hamstrings', 'quadriceps'],
    secondaryMuscles: ['lower back'],
    progressionType: 'double-progression',
    muscleGroup: 'glutes',
    equipment: ['trap-bar'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 5, maxReps: 8 },
    intendedFeeling:
      'You should feel your glutes, hamstrings, and quads driving the lift together, with your torso staying rigid throughout.',
    cues: [
      'Set your hips and shoulders in position before you pull',
      'Push the floor away with your legs to start the lift',
      'Keep the bar close to your body throughout',
      'Stand tall at the top, squeezing your glutes, without leaning back',
    ],
    commonMistakes: [
      'Rounding the lower back to start the pull',
      'Letting the hips shoot up first, turning it into a stiff leg pull',
      'Hyperextending the lower back at lockout',
    ],
    substitutions: ['conventional-deadlift', 'sumo-deadlift'],
  },
  {
    id: 'sumo-deadlift',
    name: 'Sumo Deadlift',
    category: 'strength',
    primaryMuscles: ['glutes', 'adductors'],
    secondaryMuscles: ['hamstrings', 'lower back'],
    progressionType: 'double-progression',
    muscleGroup: 'glutes',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 5, maxReps: 8 },
    intendedFeeling:
      'You should feel your glutes and inner thighs driving the pull from a wide stance, with a more upright torso than a conventional deadlift.',
    cues: [
      'Set a wide stance with your toes turned out',
      'Grip inside your knees and set your hips down and back',
      'Push your knees out in line with your toes as you pull',
      'Drive the floor away and stand tall at the top',
    ],
    commonMistakes: [
      'Letting the knees cave inward during the pull',
      'Rounding the lower back to reach the bar',
      'Shooting the hips up first instead of driving evenly',
    ],
    substitutions: ['conventional-deadlift', 'trap-bar-deadlift'],
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    category: 'strength',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    progressionType: 'double-progression',
    muscleGroup: 'glutes',
    equipment: ['barbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your glutes driving the bar up and squeezing hard at the top, with your lower back staying neutral, not arching to finish the rep.',
    cues: [
      'Set your upper back against the bench, bar rolled up over your hips',
      'Plant your feet flat, shins close to vertical at the top',
      'Drive through your heels and squeeze your glutes at the top',
      'Keep your ribs down rather than arching the lower back to finish',
    ],
    commonMistakes: [
      'Hyperextending the lower back instead of squeezing the glutes',
      'Pushing through the toes instead of the heels',
      'Using a shortened range that never reaches full hip extension',
    ],
    substitutions: ['barbell-glute-bridge', 'machine-hip-thrust'],
  },
  {
    id: 'barbell-glute-bridge',
    name: 'Barbell Glute Bridge',
    category: 'hypertrophy',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    progressionType: 'double-progression',
    muscleGroup: 'glutes',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel the same glute-driven finish as a hip thrust, from the floor instead of a bench.',
    cues: [
      'Lie back with the bar rolled over your hips and knees bent',
      'Plant your feet flat, shoulder width apart',
      'Drive through your heels and squeeze your glutes at the top',
      'Lower under control rather than dropping the bar',
    ],
    commonMistakes: [
      'Arching the lower back to gain height instead of squeezing the glutes',
      'Using a range so short the glutes never fully extend',
      'Pushing through the toes instead of the heels',
    ],
    substitutions: ['hip-thrust', 'glute-bridge'],
  },
  {
    id: 'machine-hip-thrust',
    name: 'Machine Hip Thrust',
    category: 'hypertrophy',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    progressionType: 'double-progression',
    muscleGroup: 'glutes',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your glutes driving the pad up and squeezing at the top, with the machine keeping the bar path fixed so you can focus entirely on the squeeze.',
    cues: [
      'Set your upper back against the pad, feet flat on the platform',
      'Drive through your heels to extend your hips',
      'Squeeze your glutes hard at the top of every rep',
      'Lower under control back to a full stretch',
    ],
    commonMistakes: [
      'Arching the lower back instead of finishing with the glutes',
      'Using a partial range that skips the top squeeze',
      'Rushing reps so the squeeze never registers',
    ],
    substitutions: ['hip-thrust', 'barbell-glute-bridge'],
  },
  {
    id: 'cable-pull-through',
    name: 'Cable Pull-Through',
    category: 'hypertrophy',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lower back'],
    progressionType: 'double-progression',
    muscleGroup: 'glutes',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your glutes and hamstrings driving your hips forward from a hinged position, with the cable pulling you back into the stretch each rep.',
    cues: [
      'Face away from the stack with the cable between your legs',
      'Hinge at the hips, letting the cable pull you back into a stretch',
      'Drive your hips forward to stand, squeezing the glutes',
      'Keep your spine neutral throughout the hinge',
    ],
    commonMistakes: [
      'Squatting the weight instead of hinging at the hips',
      'Rounding the lower back at the bottom of the stretch',
      'Using the arms to pull the rope through instead of the hips',
    ],
  },
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'hypertrophy',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lower back', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'glutes',
    equipment: ['kettlebell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20 },
    intendedFeeling:
      'You should feel your glutes and hamstrings snapping your hips forward to drive the kettlebell, with your arms staying relaxed and just along for the ride.',
    cues: [
      'Hinge the kettlebell back between your legs',
      'Snap your hips forward explosively to drive the bell up',
      'Keep your arms relaxed, they only guide the bell',
      'Let the bell float back down before the next hinge',
    ],
    commonMistakes: [
      'Squatting the movement instead of hinging',
      'Using the arms and shoulders to lift the bell',
      'Overextending the lower back at the top instead of stopping at hip extension',
    ],
  },
  {
    id: 'cable-kickback',
    name: 'Cable Kickback',
    category: 'hypertrophy',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    progressionType: 'double-progression',
    muscleGroup: 'glutes',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 15, perSide: true },
    intendedFeeling:
      'You should feel a strict, isolated glute squeeze as your leg extends back, without your lower back arching to add range.',
    cues: [
      'Hinge forward slightly and brace your core against the frame',
      'Kick your leg straight back, leading with the heel',
      'Squeeze the glute hard at full extension',
      'Return under control rather than swinging back',
    ],
    commonMistakes: [
      'Arching the lower back to gain extra range',
      'Swinging the leg with momentum instead of a controlled squeeze',
      'Standing too upright, which shifts work off the glute',
    ],
  },
  {
    id: 'single-leg-glute-bridge',
    name: 'Single-Leg Glute Bridge',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    progressionType: 'double-progression',
    muscleGroup: 'glutes',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15, perSide: true },
    intendedFeeling:
      'You should feel your glute driving the lift on the working leg, with your hips staying level and square.',
    cues: [
      'Keep your working foot flat and drive through the heel',
      'Squeeze the glute hard at the top',
      'Keep your hips level, do not let the free side drop or rotate',
      'Lower under control rather than dropping down',
    ],
    commonMistakes: [
      'Letting the hips rotate or tilt toward the non working side',
      'Overarching the lower back to gain height',
      'Pushing through the toes instead of the heel',
    ],
    substitutions: ['glute-bridge', 'hip-thrust'],
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    category: 'hypertrophy',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    progressionType: 'double-progression',
    muscleGroup: 'glutes',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20 },
    intendedFeeling:
      'You should feel your glutes driving the lift and squeezing hard at the top, with no help from arching your lower back.',
    cues: [
      'Lie on your back with knees bent, feet flat',
      'Drive through your heels to lift your hips',
      'Squeeze your glutes hard at the top',
      'Lower under control rather than dropping down',
    ],
    commonMistakes: [
      'Arching the lower back instead of squeezing the glutes',
      'Pushing through the toes instead of the heels',
      'Using a rushed, bouncy tempo',
    ],
    substitutions: ['barbell-glute-bridge', 'single-leg-glute-bridge'],
  },
  {
    id: 'frog-pump',
    name: 'Frog Pump',
    category: 'hypertrophy',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['adductors'],
    progressionType: 'double-progression',
    muscleGroup: 'glutes',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 15, maxReps: 20 },
    intendedFeeling:
      'You should feel a concentrated glute squeeze with your hips turned out and the soles of your feet together, more contraction than range.',
    cues: [
      'Lie on your back with the soles of your feet together, knees open',
      'Drive your hips up, squeezing your glutes at the top',
      'Keep your knees relaxed open rather than forcing them down',
      'Lower under control back to the floor',
    ],
    commonMistakes: [
      'Rushing the tempo instead of pausing at the squeeze',
      'Letting the lower back arch to gain height',
      'Forcing the knees down instead of letting them stay relaxed',
    ],
  },
  {
    id: '45-degree-hip-extension',
    name: '45 Degree Hip Extension',
    category: 'hypertrophy',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'lower back'],
    progressionType: 'double-progression',
    muscleGroup: 'glutes',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your glutes finishing the top of each rep with a hard squeeze, and your hamstrings and lower back stabilizing through the hinge.',
    cues: [
      'Set your hips at the edge of the pad with a slight forward hinge to start',
      'Drive up by extending your hips, squeezing the glutes at the top',
      'Keep a neutral spine throughout, do not hyperextend at the top',
      'Lower under control back to the starting hinge',
    ],
    commonMistakes: [
      'Hyperextending the lower back to add range at the top',
      'Rounding the back at the bottom of the hinge',
      'Rushing reps so the top squeeze never registers',
    ],
  },

  // --- Hips: adduction, abduction, flexion, and stabilization ---
  {
    id: 'adductor-machine',
    name: 'Adductor Machine',
    category: 'hypertrophy',
    primaryMuscles: ['adductors'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'hips',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 15 },
    intendedFeeling:
      'You should feel steady tension along your inner thighs as your legs squeeze together, without strain anywhere else.',
    cues: [
      'Set the range so your legs start comfortably open',
      'Squeeze your legs together under control',
      'Pause briefly at full squeeze',
      'Keep the range within what feels controlled, and increase it gradually',
    ],
    commonMistakes: [
      'Starting from an aggressively wide range before it feels ready',
      'Using momentum to slam the pads together',
      'Rushing the return instead of controlling it',
    ],
    substitutions: ['cable-hip-adduction'],
  },
  {
    id: 'hip-abduction',
    name: 'Hip Abduction',
    category: 'hypertrophy',
    primaryMuscles: ['glute medius'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'hips',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 15 },
    intendedFeeling:
      'You should feel the side of your hip working as your legs press outward, not your lower back or inner thigh.',
    cues: [
      'Sit tall with your back flat against the pad',
      'Press your knees outward under control',
      'Pause briefly at the widest point',
      'Return slowly rather than letting the pads snap back',
    ],
    commonMistakes: [
      'Leaning the torso to help push the weight',
      'Using a fast, bouncing motion instead of a controlled press',
      'Only using a short range of motion',
    ],
    substitutions: ['side-lying-hip-abduction', 'banded-lateral-walk'],
  },
  {
    id: 'short-lever-copenhagen-plank',
    name: 'Short-Lever Copenhagen Plank',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['adductors'],
    secondaryMuscles: ['obliques'],
    progressionType: 'double-progression',
    muscleGroup: 'hips',
    equipment: ['bench'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 15, maxSeconds: 30, perSide: true },
    intendedFeeling:
      'You should feel steady tension along the inner thigh of your top leg, with your hips staying level and controlled.',
    cues: [
      'Stack your hips and shoulders in a straight line',
      'Rest your top foot on the bench and lift your bottom leg to hold position',
      'Keep your hips square, do not let them rotate open',
      'Work within a comfortable range and only extend it gradually',
    ],
    commonMistakes: [
      'Letting the hips sag or rotate to compensate',
      'Rushing to a longer lever before the current one feels controlled',
      'Holding the breath instead of breathing through the hold',
    ],
    substitutions: ['long-lever-copenhagen-plank'],
  },
  {
    id: 'long-lever-copenhagen-plank',
    name: 'Long-Lever Copenhagen Plank',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['adductors'],
    secondaryMuscles: ['obliques'],
    progressionType: 'double-progression',
    muscleGroup: 'hips',
    equipment: ['bench'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 15, maxSeconds: 30, perSide: true },
    intendedFeeling:
      'You should feel significantly more inner-thigh demand than the short-lever version, with your hips still staying level and square.',
    cues: [
      'Rest your top shin or foot further down the bench than the short-lever version',
      'Stack your hips and shoulders in a straight line',
      'Keep your hips square, resisting rotation',
      'Only progress here once the short-lever hold is fully controlled',
    ],
    commonMistakes: [
      'Moving to the long lever before the short lever is controlled',
      'Letting the hips sag or open up',
      'Holding the breath through the hold',
    ],
    substitutions: ['short-lever-copenhagen-plank'],
  },
  {
    id: 'side-lying-hip-abduction',
    name: 'Side-Lying Hip Abduction',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['glute medius'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'hips',
    equipment: ['band'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20, perSide: true },
    intendedFeeling:
      'You should feel the side of your hip lifting your leg against the band, with your hips stacked and stable, not rocking backward.',
    cues: [
      'Lie on your side with your hips stacked directly on top of each other',
      'Keep your top leg straight and lift it without rotating the hip back',
      'Lift only as high as you can control without rocking',
      'Lower under control rather than dropping the leg',
    ],
    commonMistakes: [
      'Rocking the top hip back to lift the leg higher',
      'Using momentum to swing the leg up',
      'Letting the working leg rotate forward or backward',
    ],
    substitutions: ['hip-abduction', 'banded-lateral-walk'],
  },
  {
    id: 'banded-lateral-walk',
    name: 'Banded Lateral Walk',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['glute medius'],
    secondaryMuscles: ['adductors'],
    progressionType: 'double-progression',
    muscleGroup: 'hips',
    equipment: ['band'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15, perSide: true },
    intendedFeeling:
      'You should feel constant tension in the side of your hips as you step sideways against the band, with your knees staying pressed outward.',
    cues: [
      'Set a quarter-squat position and keep it the whole set',
      'Step sideways under control, keeping tension on the band both directions',
      'Keep your knees pressed outward against the band',
      'Avoid letting your feet drift together between steps',
    ],
    commonMistakes: [
      'Standing tall and losing the squat position',
      'Letting the knees cave inward between steps',
      'Taking steps too big to control the band tension',
    ],
    substitutions: ['side-lying-hip-abduction', 'hip-abduction'],
  },
  {
    id: 'clamshell',
    name: 'Clamshell',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['glute medius'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'hips',
    equipment: ['band'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 15, maxReps: 20, perSide: true },
    intendedFeeling:
      'You should feel an isolated squeeze in the side of your hip as your top knee opens, with your pelvis staying still, not rocking back.',
    cues: [
      'Lie on your side with hips and knees bent, feet together',
      'Keep your pelvis still and open your top knee like a clamshell',
      'Squeeze at the top of the movement',
      'Lower under control without letting the pelvis roll back',
    ],
    commonMistakes: [
      'Rocking the pelvis backward to open the knee further',
      'Using a fast, bouncing tempo',
      'Letting the feet separate instead of staying together',
    ],
  },
  {
    id: 'cable-hip-adduction',
    name: 'Cable Hip Adduction',
    category: 'hypertrophy',
    primaryMuscles: ['adductors'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'hips',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 15, perSide: true },
    intendedFeeling:
      'You should feel your inner thigh pulling your leg across your body against steady cable resistance, with your torso staying still.',
    cues: [
      'Attach the cuff to your ankle with the cable out to the side',
      'Pull your leg across your body under control',
      'Keep your torso upright, holding the frame for balance only',
      'Return to the start slowly rather than letting the cable snap it back',
    ],
    commonMistakes: [
      'Using the torso to help swing the leg across',
      'Letting the cable yank the leg back on the return',
      'Standing too close, cutting the range short',
    ],
    substitutions: ['adductor-machine'],
  },
  {
    id: 'cable-hip-flexion',
    name: 'Cable Hip Flexion',
    category: 'hypertrophy',
    primaryMuscles: ['hip flexors'],
    secondaryMuscles: ['quads'],
    progressionType: 'double-progression',
    muscleGroup: 'hips',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 15, perSide: true },
    intendedFeeling:
      'You should feel your hip flexor driving your knee up against resistance, with your standing leg and torso staying stable throughout.',
    cues: [
      'Attach the cuff to your ankle with the cable behind you',
      'Drive your knee up and forward under control',
      'Keep your torso tall rather than leaning back to help',
      'Lower under control back to the start',
    ],
    commonMistakes: [
      'Leaning the torso back to help drive the knee up',
      'Letting the cable yank the leg back down',
      'Rushing reps instead of controlling both directions',
    ],
  },
  {
    id: 'standing-banded-hip-flexor-march',
    name: 'Standing Banded Hip Flexor March',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['hip flexors'],
    secondaryMuscles: ['core'],
    progressionType: 'double-progression',
    muscleGroup: 'hips',
    equipment: ['band'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15, perSide: true },
    intendedFeeling:
      'You should feel your hip flexor lifting your knee against band resistance while your standing leg and core stay stable and square.',
    cues: [
      'Anchor the band low and loop it around the working foot or knee',
      'Stand tall with your core braced before you drive the knee up',
      'Drive the knee up to about hip height under control',
      'Lower under control rather than letting the band snap the leg down',
    ],
    commonMistakes: [
      'Leaning the torso backward to help lift the knee',
      'Letting the standing hip drop or rotate',
      'Rushing the tempo instead of controlling both directions',
    ],
  },
];
