import type { CatalogExercise } from '../program-types';

// Quad-dominant knee-extension and single-leg work. Squat pattern variants,
// machine isolation, and single-leg/unilateral carryover for the field.

export const QUAD_EXERCISES: CatalogExercise[] = [
  // --- Barbell squat pattern ---
  {
    id: 'back-squat',
    name: 'Back Squat',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'lower back'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 5, maxReps: 8 },
    intendedFeeling:
      'You should feel your quads and glutes driving out of the bottom, with your torso staying rigid the whole rep, not your lower back rounding under the bar.',
    cues: [
      'Set your feet just outside shoulder width and brace before you unrack',
      'Break at the hips and knees together, sitting down more than back',
      'Descend until your hip crease is at or below your knee',
      'Drive the floor away and keep your chest up through the whole ascent',
    ],
    commonMistakes: [
      'Letting the knees cave inward on the way up',
      'Rounding the lower back to squat deeper than mobility allows',
      'Rising with the hips first and turning it into a good morning',
    ],
    substitutions: ['front-squat', 'hack-squat'],
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 5, maxReps: 8 },
    intendedFeeling:
      'You should feel the load concentrated on your quads with an upright torso, and your core bracing hard to keep your chest from collapsing forward.',
    cues: [
      'Rest the bar across your front delts, elbows high',
      'Keep your chest tall throughout the descent',
      'Sit straight down between your hips rather than back',
      'Drive up while keeping the elbows lifted',
    ],
    commonMistakes: [
      'Letting the elbows drop, which tips the bar forward',
      'Leaning the torso forward to compensate for ankle mobility',
      'Rushing the unrack and losing bar position before the first rep',
    ],
    substitutions: ['back-squat', 'goblet-squat'],
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    category: 'hypertrophy',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your quads working through a full range with an upright torso, and the dumbbell acting as a counterbalance rather than something you have to muscle up.',
    cues: [
      'Hold the dumbbell vertically against your chest',
      'Sit down between your hips, keeping your elbows inside your knees at the bottom',
      'Keep your chest up and your heels planted',
      'Drive up through your whole foot',
    ],
    commonMistakes: [
      'Letting the torso fold forward as the legs fatigue',
      'Rising onto the toes instead of pushing through the whole foot',
      'Stopping the descent well above parallel',
    ],
    substitutions: ['front-squat', 'split-squat'],
  },
  {
    id: 'safety-bar-squat',
    name: 'Safety Bar Squat',
    category: 'strength',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'upper back'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 10 },
    intendedFeeling:
      'You should feel an upright, quad-dominant squat with the load sitting further forward than a back squat, and your upper back working to keep the bar from pitching you forward.',
    cues: [
      'Let the yoke settle evenly across your shoulders, hands relaxed on the handles',
      'Brace before you unrack, the forward-shifted load rewards a tight core',
      'Squat with a slightly more upright torso than a standard back squat',
      'Drive up evenly through both feet',
    ],
    commonMistakes: [
      'Letting the shoulders round forward under the forward load',
      'Using the handles to pull rather than bracing the trunk',
      'Rushing depth before mobility allows it',
    ],
  },
  {
    id: 'smith-machine-squat',
    name: 'Smith Machine Squat',
    category: 'hypertrophy',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['smith-machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your quads doing the work through a fixed, controlled path, without needing to balance the bar path yourself.',
    cues: [
      'Set your feet slightly forward of the bar path to keep tension on the quads',
      'Lower under control to at least parallel',
      'Keep your heels planted the whole rep',
      'Drive up without locking the knees out hard at the top',
    ],
    commonMistakes: [
      'Standing directly under the bar and turning it into a leg press with your back',
      'Only working a short partial range',
      'Letting the hips shoot back to chase more weight than the fixed path suits',
    ],
    substitutions: ['back-squat', 'hack-squat'],
  },
  {
    id: 'belt-squat',
    name: 'Belt Squat',
    category: 'hypertrophy',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel the load pulling straight down through your hips and legs with no compression on your spine, freeing your quads and glutes to do all the work.',
    cues: [
      'Stand tall on the platforms with the belt hanging free at the bottom',
      'Squat down keeping your torso upright',
      'Keep the load traveling straight through your hips, not swinging',
      'Drive up through your whole foot to standing',
    ],
    commonMistakes: [
      'Rushing reps and letting the belt swing rather than tracking straight',
      'Only squatting through a shallow partial range',
      'Gripping the frame to help push instead of driving with the legs',
    ],
  },
  {
    id: 'pendulum-squat',
    name: 'Pendulum Squat',
    category: 'hypertrophy',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel a deep, quad-dominant stretch at the bottom of the arc with your back fully supported by the pad.',
    cues: [
      'Keep your back flat against the pad throughout',
      'Lower under control into a full stretch at the bottom',
      'Keep your knees tracking over your toes',
      'Drive up through your whole foot rather than just your toes',
    ],
    commonMistakes: [
      'Cutting the bottom stretch short',
      'Letting the knees cave inward under the arc',
      'Bouncing out of the bottom instead of controlling it',
    ],
  },

  // --- Machine isolation ---
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    category: 'hypertrophy',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 15 },
    intendedFeeling:
      'You should feel your quads contracting hard through a full range, with a clear squeeze at the top of every rep.',
    cues: [
      'Set the pad just above your ankles',
      'Extend through a full range and squeeze at the top',
      'Control the weight back down to a full stretch',
      'Keep your hips flat against the seat throughout',
    ],
    commonMistakes: [
      'Using momentum to kick the weight up',
      'Letting the hips lift off the seat',
      'Cutting the range short at the top or bottom',
    ],
  },
  {
    id: 'single-leg-leg-extension',
    name: 'Single-Leg Leg Extension',
    category: 'hypertrophy',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 15, perSide: true },
    intendedFeeling:
      'You should feel one quad working through a full, isolated range, with no help from the other leg to finish the rep.',
    cues: [
      'Set the pad just above your ankle on the working leg',
      'Extend through a full range and squeeze at the top',
      'Keep the resting leg relaxed and out of the way',
      'Control the negative back to a full stretch',
    ],
    commonMistakes: [
      'Letting the hips twist to help drive the weight up',
      'Rushing through reps instead of controlling the range',
      'Using a load that forces momentum on one leg',
    ],
    substitutions: ['leg-extension'],
  },
  {
    id: 'single-leg-leg-press',
    name: 'Single-Leg Leg Press',
    category: 'hypertrophy',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12, perSide: true },
    intendedFeeling:
      'You should feel one leg controlling the full range on its own, with your hips staying square instead of shifting toward the working side.',
    cues: [
      'Keep your hips level against the seat back',
      'Lower until your knee reaches a deep, controlled range',
      'Drive through your whole foot, not just your toes',
      'Avoid locking the knee out hard at the top',
    ],
    commonMistakes: [
      'Letting the hip rotate or shift to help the working leg',
      'Only using a shallow partial range',
      'Slamming the knee straight at lockout',
    ],
    substitutions: ['leg-press'],
  },

  // --- Preserved: unilateral and general strength ---
  {
    id: 'hack-squat',
    name: 'Hack Squat',
    category: 'hypertrophy',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel the load across your quads through the full range, especially near the bottom of the movement.',
    cues: [
      'Keep your feet flat and your back against the pad',
      'Lower until your thighs are at least parallel, under control',
      'Drive through the middle of your foot to stand up',
      'Keep your knees tracking over your toes',
    ],
    commonMistakes: [
      'Only squatting through a short partial range',
      'Letting the knees cave inward on the way up',
      'Bouncing out of the bottom instead of controlling the descent',
    ],
    substitutions: ['back-squat', 'smith-machine-squat'],
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    category: 'hypertrophy',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your quads and glutes working through a deep, controlled range, especially near the bottom.',
    cues: [
      'Lower the sled until your knees reach a deep, controlled range',
      'Keep your lower back flat against the pad',
      'Drive through your whole foot to press back up',
      'Avoid locking your knees out hard at the top',
    ],
    commonMistakes: [
      'Only using a short partial range',
      'Letting the lower back round off the pad at the bottom',
      'Slamming the knees straight and locking out hard at the top',
    ],
    substitutions: ['single-leg-leg-press', 'hack-squat'],
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'hypertrophy',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['dumbbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12, perSide: true },
    intendedFeeling:
      "You should feel your front leg's quad and glute working through the whole range, with your back leg only there for balance.",
    cues: [
      'Keep most of your weight on your front foot',
      'Lower straight down until your back knee nearly touches the floor',
      'Keep your torso upright for more quad, lean forward slightly for more glute',
      'Drive through your front heel to stand',
    ],
    commonMistakes: [
      'Letting the back leg push and take over the work',
      'Only descending part way',
      'Letting the front knee cave inward',
    ],
    substitutions: ['split-squat', 'reverse-lunge'],
  },
  {
    id: 'split-squat',
    name: 'Split Squat',
    category: 'hypertrophy',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12, perSide: true },
    intendedFeeling:
      'You should feel your front leg working through the whole range from a fixed stance, without needing to balance a rear foot elevation.',
    cues: [
      'Set a stance long enough that your front shin stays close to vertical at the bottom',
      'Lower straight down under control',
      'Keep most of your weight on the front foot',
      'Drive through the front heel to stand',
    ],
    commonMistakes: [
      'Taking too short a stance and turning it into a knee-dominant lunge',
      'Letting the front knee drift inward',
      'Pushing off the back foot to help finish the rep',
    ],
    substitutions: ['bulgarian-split-squat', 'reverse-lunge'],
  },
  {
    id: 'step-up',
    name: 'Step-Up',
    category: 'hypertrophy',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['dumbbell', 'box'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12, perSide: true },
    intendedFeeling:
      'You should feel your working leg driving your whole bodyweight up onto the box, with the trailing leg contributing almost nothing.',
    cues: [
      'Place your whole foot flat on the box before driving up',
      'Stand up through the working leg without pushing off the trailing foot',
      'Keep your torso upright rather than leaning forward to generate momentum',
      'Lower back down under control',
    ],
    commonMistakes: [
      'Pushing off the trailing foot to help finish the rep',
      'Using a box high enough that momentum replaces control',
      'Leaning the torso forward to launch off the floor',
    ],
  },
  {
    id: 'reverse-lunge',
    name: 'Reverse Lunge',
    category: 'hypertrophy',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12, perSide: true },
    intendedFeeling:
      "You should feel your front leg's quad and glute controlling the descent and driving you back up.",
    cues: [
      'Step back and lower your back knee toward the floor under control',
      'Keep your front shin close to vertical',
      'Drive through your front heel to return to standing',
      'Keep your torso upright throughout',
    ],
    commonMistakes: [
      'Letting the front knee cave inward',
      'Pushing off the back leg instead of the front',
      'Taking too short a step and cutting the range short',
    ],
    substitutions: ['walking-lunge', 'split-squat'],
  },
  {
    id: 'walking-lunge',
    name: 'Walking Lunge',
    category: 'hypertrophy',
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 12, perSide: true },
    intendedFeeling:
      "You should feel your front leg's quad and glute doing the work on each step, with your torso staying upright and controlled.",
    cues: [
      'Step far enough forward that your front shin stays close to vertical',
      'Lower your back knee toward the floor under control',
      'Drive through your front heel to stand and step into the next rep',
      'Keep your torso tall rather than leaning forward',
    ],
    commonMistakes: [
      'Taking short, choppy steps that limit range',
      'Letting the front knee cave inward',
      'Bouncing off the back leg instead of pressing through the front',
    ],
    substitutions: ['reverse-lunge'],
  },
  {
    id: 'lateral-lunge',
    name: 'Lateral Lunge',
    category: 'hypertrophy',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['adductors'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12, perSide: true },
    intendedFeeling:
      'You should feel your working leg loading through the quad and inner thigh as you sit into it sideways, with the straight leg only stretching, not bearing weight.',
    cues: [
      'Step wide to the side and sit your hips back and down over the bent knee',
      'Keep the straight leg long with the foot flat',
      'Keep your chest up rather than folding forward',
      'Push off the working leg to return to center',
    ],
    commonMistakes: [
      'Letting the working knee drift past the toes and cave inward',
      'Rounding the back to reach further sideways',
      'Rushing the return instead of controlling it',
    ],
  },

  // --- Bodyweight and isometric ---
  {
    id: 'sissy-squat',
    name: 'Sissy Squat',
    category: 'calisthenics',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['core'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 6, maxReps: 12 },
    intendedFeeling:
      'You should feel an intense, isolated stretch and contraction through your quads as your knees travel forward and your torso leans back.',
    cues: [
      'Hold something stable for balance if needed',
      'Let your knees travel forward as your torso leans back, keeping hips extended',
      'Lower only as far as your quads can control',
      'Drive back up leading with the quads, not by yanking on support',
    ],
    commonMistakes: [
      'Bending at the hips instead of keeping them extended',
      'Descending faster than control allows',
      'Relying entirely on the arms to pull back up',
    ],
  },
  {
    id: 'heel-elevated-squat',
    name: 'Heel-Elevated Squat',
    category: 'hypertrophy',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel more of the load shift onto your quads than a flat-footed squat, with an easier, more upright torso position.',
    cues: [
      'Set a small plate or wedge under both heels',
      'Keep your torso tall as you descend',
      'Sit down between your hips rather than back',
      'Drive up through the whole foot, not just the toes',
    ],
    commonMistakes: [
      'Using a wedge high enough to feel unstable',
      'Letting the knees track far past a controlled range',
      'Rushing the descent instead of controlling it',
    ],
  },
  {
    id: 'wall-sit',
    name: 'Wall Sit',
    category: 'hypertrophy',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'quads',
    equipment: ['bodyweight'],
    defaultPrescription: { type: 'hold', sets: 3, minSeconds: 30, maxSeconds: 60 },
    intendedFeeling:
      'You should feel a steady, building burn across your quads as you hold the position, with your lower back staying flat against the wall.',
    cues: [
      'Set your thighs parallel to the floor, knees over ankles',
      'Press your lower back flat against the wall',
      'Keep your weight in your heels',
      'Breathe steadily through the hold rather than bracing your breath',
    ],
    commonMistakes: [
      'Letting the knees drift forward past the toes',
      'Arching the lower back off the wall',
      'Setting the hold too shallow to load the quads',
    ],
  },
];
