import type { CatalogExercise } from '../program-types';

/**
 * Shoulder exercise library (R10). Preserves Seated Dumbbell Shoulder
 * Press, Cable Lateral Raise, Machine Shoulder Press, Face Pull, Reverse
 * Cable Fly, Reverse Pec Deck, and Rear-Delt Fly from the pre-R10 catalog
 * verbatim (name/category/muscles/progression/guidance untouched), adding
 * only muscleGroup, equipment, and defaultPrescription. Every other entry
 * is new library content.
 */
export const SHOULDER_EXERCISES: CatalogExercise[] = [
  // --- Overhead pressing ---
  {
    id: 'overhead-barbell-press',
    name: 'Overhead Barbell Press',
    category: 'strength',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'upper chest'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['barbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 5, maxReps: 8 },
    intendedFeeling:
      'You should feel your shoulders driving the bar straight overhead with your core braced hard to keep your ribs from flaring.',
    cues: [
      'Brace your core and squeeze your glutes before pressing',
      'Press the bar in a straight line, moving your head back slightly to clear it',
      'Finish with the bar over the crown of your head and your arms locked',
      'Lower under control back to your upper chest',
    ],
    commonMistakes: [
      'Leaning back excessively and turning it into an incline press',
      'Flaring the ribs and losing core brace to gain range',
      'Pressing the bar forward instead of straight up',
    ],
    substitutions: ['standing-dumbbell-press', 'seated-dumbbell-shoulder-press', 'machine-shoulder-press'],
  },
  {
    id: 'standing-dumbbell-press',
    name: 'Standing Dumbbell Press',
    category: 'hypertrophy',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'core'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel your shoulders pressing the load overhead while your core and legs work to keep your whole body stable and upright.',
    cues: [
      'Brace your core before unracking the dumbbells to your shoulders',
      'Press up and slightly inward without leaning back',
      'Keep your ribs down throughout the press',
      'Lower under control to shoulder height',
    ],
    commonMistakes: [
      'Leaning back to use momentum out of the bottom',
      'Pressing one arm ahead of the other',
      'Flaring the ribs to gain a few extra inches of range',
    ],
    substitutions: ['seated-dumbbell-shoulder-press', 'arnold-press'],
  },
  {
    id: 'seated-dumbbell-shoulder-press',
    name: 'Seated Dumbbell Shoulder Press',
    category: 'hypertrophy',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel the load across the front and side of your shoulders through the whole range, with your torso staying still.',
    cues: [
      'Brace your core before you press',
      'Press the dumbbells up and slightly inward, not straight out to the sides',
      'Lower until your upper arms are about level with your shoulders',
      'Keep your ribs down, do not lean back to finish the rep',
    ],
    commonMistakes: [
      'Leaning back and turning it into an incline press',
      'Using leg drive or a bounce out of the bottom',
      'Only pressing through the top half of the range',
    ],
    muscleGroup: 'shoulders',
    equipment: ['dumbbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    substitutions: ['standing-dumbbell-press', 'machine-shoulder-press'],
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    category: 'hypertrophy',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'front delts'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['dumbbell', 'bench'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    intendedFeeling:
      'You should feel the rotation add extra work to the front and side of the shoulder through a longer range than a standard press.',
    cues: [
      'Start with palms facing you at shoulder height',
      'Rotate your palms outward as you press up',
      'Finish with palms facing forward and arms locked overhead',
      'Reverse the rotation on the way down under control',
    ],
    commonMistakes: [
      'Rushing the rotation instead of controlling it through the range',
      'Leaning back to help finish the press',
      'Using too much weight and losing the rotation entirely',
    ],
    substitutions: ['standing-dumbbell-press', 'seated-dumbbell-shoulder-press'],
  },
  {
    id: 'landmine-press',
    name: 'Landmine Press',
    category: 'hypertrophy',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'upper chest'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['barbell', 'other'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12, perSide: true },
    intendedFeeling:
      'You should feel your shoulder pressing along an angled path that feels easier on the joint than a straight overhead press.',
    cues: [
      'Set the bar at chest height and press along its natural arc',
      'Brace your core, especially if pressing from a half kneeling position',
      'Press up and slightly forward, following the bar path',
      'Lower under control back to the shoulder',
    ],
    commonMistakes: [
      'Fighting the natural arc by pressing straight up',
      'Letting the torso rotate to help finish the press',
      'Using a stance that lets the hips shift instead of staying braced',
    ],
    substitutions: ['standing-dumbbell-press', 'machine-shoulder-press'],
  },
  {
    id: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    category: 'hypertrophy',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel your shoulders driving the press through the full range, with your triceps assisting at lockout.',
    cues: [
      'Set the seat so the handles start level with your shoulders',
      'Press up without shrugging your shoulders toward your ears',
      'Extend fully at the top without locking out aggressively',
      'Lower under control to a full stretch',
    ],
    commonMistakes: [
      'Shrugging the traps to help start the press',
      'Only using the top half of the range',
      'Rushing the lowering phase',
    ],
    muscleGroup: 'shoulders',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 8, maxReps: 12 },
    substitutions: ['seated-dumbbell-shoulder-press', 'overhead-barbell-press'],
  },

  // --- Side delt isolation ---
  {
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    category: 'hypertrophy',
    primaryMuscles: ['side delts'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20 },
    intendedFeeling:
      'You should feel tension on the side of your shoulder as your arms rise, not in your traps.',
    cues: [
      'Start with a slight bend in the elbows and hold it',
      'Lead with your elbows, not your hands',
      'Raise only to about shoulder height',
      'Lower under control rather than dropping the weight',
    ],
    commonMistakes: [
      'Swinging the torso to generate momentum',
      'Shrugging the traps to help lift the weight',
      'Raising above shoulder height so the trap takes over',
    ],
    substitutions: ['cable-lateral-raise', 'machine-lateral-raise', 'leaning-cable-lateral-raise'],
  },
  {
    id: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    category: 'hypertrophy',
    primaryMuscles: ['lateral deltoid'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel tension on the side of your shoulder through the whole arc, not in your traps or forearm.',
    cues: [
      'Set the cable low and stand side on to it',
      'Lead with your elbow, not your hand',
      'Raise only to about shoulder height',
      'Keep a slight bend in the elbow and control the lowering phase',
    ],
    commonMistakes: [
      'Shrugging the traps to help lift the weight',
      'Swinging the torso to generate momentum',
      'Raising too high so the trap takes over at the top',
    ],
    muscleGroup: 'shoulders',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20 },
    substitutions: ['dumbbell-lateral-raise', 'leaning-cable-lateral-raise'],
  },
  {
    id: 'leaning-cable-lateral-raise',
    name: 'Leaning Cable Lateral Raise',
    category: 'hypertrophy',
    primaryMuscles: ['side delts'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20 },
    intendedFeeling:
      'You should feel the tension shift toward the top of your shoulder and stay there through a longer range than a standing raise allows.',
    cues: [
      'Hold onto a solid post and lean your torso away from the cable',
      'Lead the raise with your elbow',
      'Raise to about shoulder height, following your leaning torso line',
      'Lower under control back to the stretch',
    ],
    commonMistakes: [
      'Not leaning far enough to change the resistance curve',
      'Using the free hand to pull on the post instead of just balancing',
      'Swinging instead of a controlled raise',
    ],
    substitutions: ['cable-lateral-raise', 'dumbbell-lateral-raise'],
  },
  {
    id: 'machine-lateral-raise',
    name: 'Machine Lateral Raise',
    category: 'hypertrophy',
    primaryMuscles: ['side delts'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20 },
    intendedFeeling:
      'You should feel your side delt working through a fixed, supported path, useful for pushing close to failure without needing to stabilize the weight.',
    cues: [
      'Set the seat so the pads sit against your upper arms',
      'Raise your elbows out to about shoulder height',
      'Pause briefly at the top',
      'Lower under control rather than letting the pads drop',
    ],
    commonMistakes: [
      'Shrugging the traps to assist the raise',
      'Using momentum to jerk the pads up',
      'Only using a short partial range',
    ],
    substitutions: ['dumbbell-lateral-raise', 'cable-lateral-raise'],
  },
  {
    id: 'front-raise',
    name: 'Front Raise',
    category: 'hypertrophy',
    primaryMuscles: ['front delts'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 12, maxReps: 15 },
    intendedFeeling:
      'You should feel the front of your shoulder working as your arm raises, without your lower back arching to assist.',
    cues: [
      'Keep a slight bend in the elbow throughout',
      'Raise to about shoulder height, no higher',
      'Keep your core braced so your torso does not lean back',
      'Lower under control rather than dropping the weight',
    ],
    commonMistakes: [
      'Swinging the weight up with body momentum',
      'Raising above shoulder height and involving the traps',
      'Arching the lower back to help lift the weight',
    ],
    substitutions: ['dumbbell-lateral-raise', 'cable-y-raise'],
  },
  {
    id: 'upright-row',
    name: 'Upright Row',
    category: 'hypertrophy',
    primaryMuscles: ['side delts'],
    secondaryMuscles: ['traps'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 10, maxReps: 15 },
    intendedFeeling:
      'You should feel your side delts and traps pulling the weight up along your torso, with no pinching sensation in the front of the shoulder.',
    cues: [
      'Pull the weight up close to your torso',
      'Lead with your elbows, keeping them above your hands',
      'Stop at roughly chest height, do not force it higher',
      'Lower under control rather than dropping the weight',
    ],
    commonMistakes: [
      'Pulling the weight up too high and straining the shoulder joint',
      'Using a grip that is too narrow, increasing joint stress',
      'Swinging the torso to help the pull',
    ],
    substitutions: ['dumbbell-lateral-raise', 'face-pull'],
  },
  {
    id: 'scaption-raise',
    name: 'Scaption Raise',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['side delts', 'rotator cuff'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 12, maxReps: 20 },
    intendedFeeling:
      'You should feel light, controlled tension across the top of the shoulder in the scapular plane, with no pinching or catching sensation.',
    cues: [
      'Raise your arms at roughly a 30 degree angle in front of your body',
      'Lead with your thumbs pointing slightly up',
      'Raise only to about shoulder height',
      'Lower slowly and under full control',
    ],
    commonMistakes: [
      'Raising straight out to the side instead of the scapular plane',
      'Using weight heavy enough to force momentum into the raise',
      'Shrugging the shoulders instead of isolating the raise',
    ],
    substitutions: ['dumbbell-lateral-raise', 'external-rotation-cable'],
  },

  // --- Rear delt and upper back ---
  {
    id: 'face-pull',
    name: 'Face Pull',
    category: 'hypertrophy',
    primaryMuscles: ['rear deltoid', 'upper back'],
    secondaryMuscles: ['rotator cuff'],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel your rear shoulders and upper back working as you pull, with a slight external rotation at the end, not your arms doing the pulling.',
    cues: [
      'Pull to about eye or forehead height',
      'Lead with your elbows and pull them high and wide',
      'Finish by rotating your hands back like showing your palms behind you',
      'Keep your chest up and shoulder blades pulling together at the finish',
    ],
    commonMistakes: [
      'Pulling low toward the chest like a row instead of the face',
      'Using the biceps to yank the weight rather than the rear delts',
      'Shrugging the shoulders up toward the ears',
    ],
    muscleGroup: 'shoulders',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20 },
    substitutions: ['reverse-cable-fly', 'band-face-pull'],
  },
  {
    id: 'band-face-pull',
    name: 'Band Face Pull',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['rear delts', 'upper back'],
    secondaryMuscles: ['rotator cuff'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['band'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 15, maxReps: 25 },
    intendedFeeling:
      'You should feel the same rear delt and upper back pull as a cable face pull, with light band tension suited to a warm-up or high rep prehab set.',
    cues: [
      'Anchor the band at roughly face height',
      'Pull to your forehead, leading with your elbows',
      'Rotate your hands back at the end of the pull',
      'Return under control rather than letting the band snap back',
    ],
    commonMistakes: [
      'Pulling low toward the chest instead of the face',
      'Using a band too light to create meaningful tension',
      'Rushing through reps instead of a controlled rotation',
    ],
    substitutions: ['face-pull', 'reverse-cable-fly'],
  },
  {
    id: 'reverse-cable-fly',
    name: 'Reverse Cable Fly',
    category: 'hypertrophy',
    primaryMuscles: ['rear deltoid', 'upper back'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel your rear delts and upper back doing the work as your arms sweep apart, not your arms or lower back.',
    cues: [
      'Cross the cables and take a slight forward hinge',
      'Lead the movement with your elbows, not your hands',
      'Sweep your arms out and back in a wide arc',
      'Squeeze your shoulder blades together at the finish',
    ],
    commonMistakes: [
      'Bending the elbows heavily and turning it into a row',
      'Using momentum from the lower back to swing the arms',
      'Cutting the range short instead of finishing with the blades squeezed',
    ],
    muscleGroup: 'shoulders',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20 },
    substitutions: ['reverse-pec-deck', 'rear-delt-fly', 'face-pull'],
  },
  {
    id: 'reverse-pec-deck',
    name: 'Reverse Pec Deck',
    category: 'hypertrophy',
    primaryMuscles: ['rear deltoid', 'upper back'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel your rear delts and upper back squeezing together as your arms sweep back, not your arms pushing the pads.',
    cues: [
      'Set the seat so your arms start level with your shoulders',
      'Lead the movement with your elbows',
      'Sweep your arms back until your shoulder blades squeeze together',
      'Control the return to the stretched position',
    ],
    commonMistakes: [
      'Using so much weight the range shortens',
      'Pushing with straight, locked arms instead of leading with the elbows',
      'Letting momentum carry the arms instead of a controlled squeeze',
    ],
    muscleGroup: 'shoulders',
    equipment: ['machine'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20 },
    substitutions: ['reverse-cable-fly', 'rear-delt-fly'],
  },
  {
    id: 'rear-delt-fly',
    name: 'Rear-Delt Fly',
    category: 'hypertrophy',
    primaryMuscles: ['rear deltoid'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    intendedFeeling:
      'You should feel your rear delts working as your arms sweep back and out, not your traps or lower back.',
    cues: [
      'Hinge forward slightly and let your arms hang',
      'Lead the movement with your elbows',
      'Sweep your arms out and back until your shoulder blades come together',
      'Control the return rather than letting the weight drop',
    ],
    commonMistakes: [
      'Using momentum from the lower back to swing the weight',
      'Shrugging the traps instead of isolating the rear delts',
      'Cutting the range short at the top',
    ],
    muscleGroup: 'shoulders',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20 },
    substitutions: ['reverse-pec-deck', 'reverse-cable-fly'],
  },
  {
    id: 'rear-delt-row',
    name: 'Rear-Delt Row',
    category: 'hypertrophy',
    primaryMuscles: ['rear deltoid', 'upper back'],
    secondaryMuscles: [],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['dumbbell'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 20 },
    intendedFeeling:
      'You should feel a wide, high row biased toward the rear delts, with the elbows finishing higher and wider than a standard back row.',
    cues: [
      'Hinge forward and let your arms hang below your shoulders',
      'Pull your elbows up and out wide, higher than a normal row',
      'Squeeze your rear delts at the top',
      'Lower under control to a full stretch',
    ],
    commonMistakes: [
      'Pulling the elbows close to the torso like a lat row instead of wide',
      'Using momentum from the lower back',
      'Cutting the range short at the top',
    ],
    substitutions: ['rear-delt-fly', 'reverse-cable-fly'],
  },
  {
    id: 'cable-y-raise',
    name: 'Cable Y Raise',
    category: 'hypertrophy',
    primaryMuscles: ['side delts', 'lower traps'],
    secondaryMuscles: ['rear delts'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 3, minReps: 12, maxReps: 15 },
    intendedFeeling:
      'You should feel your shoulder and lower traps working together as your arms raise in a Y shape overhead, without your traps shrugging.',
    cues: [
      'Set the cables low and cross them in front of you',
      'Raise both arms together in a Y shape overhead',
      'Keep your shoulders down, away from your ears',
      'Lower under control back to the start',
    ],
    commonMistakes: [
      'Shrugging the shoulders up toward the ears',
      'Using too much weight and turning it into a front raise',
      'Rushing the tempo instead of a controlled raise',
    ],
    substitutions: ['front-raise', 'face-pull'],
  },

  // --- Rotator cuff and prehab ---
  {
    id: 'external-rotation-cable',
    name: 'External Rotation (Cable)',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['rotator cuff'],
    secondaryMuscles: ['rear delts'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['cable'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 12, maxReps: 20, perSide: true },
    intendedFeeling:
      'You should feel a light, controlled rotation deep in the shoulder joint, never a strain or pinch.',
    cues: [
      'Pin your elbow to your side at a 90 degree bend',
      'Rotate your forearm outward without letting the elbow drift away from your side',
      'Keep the motion slow and controlled throughout',
      'Return under control rather than letting the cable snap back',
    ],
    commonMistakes: [
      'Letting the elbow drift away from the torso during the rotation',
      'Using too much weight and losing the isolated rotation',
      'Rushing through reps instead of a slow, controlled tempo',
    ],
    substitutions: ['external-rotation-band', 'scaption-raise'],
  },
  {
    id: 'external-rotation-band',
    name: 'External Rotation (Band)',
    category: 'rehabilitation-prehab',
    primaryMuscles: ['rotator cuff'],
    secondaryMuscles: ['rear delts'],
    progressionType: 'double-progression',
    muscleGroup: 'shoulders',
    equipment: ['band'],
    defaultPrescription: { type: 'repetitions', sets: 2, minReps: 12, maxReps: 20, perSide: true },
    intendedFeeling:
      'You should feel a light, controlled rotation deep in the shoulder joint, never a strain or pinch, suited to warm-up or recovery days.',
    cues: [
      'Pin your elbow to your side at a 90 degree bend',
      'Rotate your forearm outward against the band',
      'Keep your elbow fixed against your side throughout',
      'Return slowly rather than letting the band snap back',
    ],
    commonMistakes: [
      'Letting the elbow drift away from the torso during the rotation',
      'Using a band with too much tension for a controlled rotation',
      'Rushing through reps',
    ],
    substitutions: ['external-rotation-cable', 'scaption-raise'],
  },
];
