/**
 * Regenerates the "Exercise names in the library" section of
 * PROGRAM_FORMAT.md from the real catalog, so a program written by the owner
 * (or by an LLM the owner asks for help) can pick names that match library
 * entries exactly and inherit their coaching guidance.
 *
 * The section sits between two marker comments in PROGRAM_FORMAT.md and is
 * replaced wholesale; everything outside the markers is left alone. Run
 * after any catalog change:
 *   npx tsx scripts/generate-program-format-library.ts
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { EXERCISE_CATALOG } from '../lib/program/exercise-catalog';
import { MUSCLE_GROUP_LABELS, MUSCLE_GROUP_ORDER } from '../lib/program/muscle-group-copy';
import { formatPrescriptionPreset } from '../lib/program/set-entry-fields';

const DOC_PATH = resolve(__dirname, '..', 'PROGRAM_FORMAT.md');
const START_MARKER = '<!-- library-names:start (generated by scripts/generate-program-format-library.ts, do not edit by hand) -->';
const END_MARKER = '<!-- library-names:end -->';

function renderSection(): string {
  const lines: string[] = [START_MARKER, ''];
  lines.push(
    `The library holds ${EXERCISE_CATALOG.length} exercises. Use these names exactly as written (case and punctuation are ignored when matching, but spelling is not) so the workout shows the entry's coaching guidance and history stays connected. Each name is followed by its logging preset, which is what a swap or "Add exercise" mid-workout would prescribe; a pasted program can prescribe something different. Nothing on foot is in the library (no running or sprinting), but distance lines like \`3 x 20m\` still parse.`
  );
  lines.push('');

  for (const group of MUSCLE_GROUP_ORDER) {
    const entries = EXERCISE_CATALOG.filter((exercise) => exercise.muscleGroup === group).sort((a, b) =>
      a.name.localeCompare(b.name)
    );
    if (entries.length === 0) continue;
    lines.push(`**${MUSCLE_GROUP_LABELS[group]}** (${entries.length})`);
    lines.push('');
    for (const exercise of entries) {
      lines.push(`- ${exercise.name}: ${formatPrescriptionPreset(exercise.defaultPrescription)}`);
    }
    lines.push('');
  }

  lines.push(END_MARKER);
  return lines.join('\n');
}

function main(): void {
  const doc = readFileSync(DOC_PATH, 'utf8');
  const start = doc.indexOf(START_MARKER);
  const end = doc.indexOf(END_MARKER);
  if (start === -1 || end === -1 || end < start) {
    console.error(`PROGRAM_FORMAT.md is missing the library-names markers.`);
    process.exit(1);
  }
  const updated = doc.slice(0, start) + renderSection() + doc.slice(end + END_MARKER.length);
  writeFileSync(DOC_PATH, updated, 'utf8');
  console.log(`PROGRAM_FORMAT.md library section regenerated: ${EXERCISE_CATALOG.length} exercises.`);
}

main();
